// GENERATED by scripts/content/generate.mjs from content/concetto26/official-content.json — do not edit by hand.
// Public competition text only (theme names/descriptions and the rules). Questions, hints and rewards are deliberately NOT
// here: they exist only in the database (supabase/migrations/20261006000019_official_content.sql) and reach a team only
// through the server, when the team is entitled to them.

export const OFFICIAL_THEMES = [
  {
    id: "A",
    name: "DIG INTO THE PASSWORD OF IIT ISM",
    description: "ADVANCED CRYPTOGRAPHY, NUMBER THEORY & COMBINATORICS",
  },
  {
    id: "B",
    name: "HOW BAD CAN BE HOSTEL FOOD",
    description: "PROBABILITY, STATISTICS, OPTIMIZATION AND QUEUING THEORY",
  },
  {
    id: "C",
    name: "END SEM FEAR TAKEOVER",
    description: "Engineering Mathematics, Calculus, and Differential Equations",
  },
  {
    id: "D",
    name: "WHAT IS THE SIZE OF THE CAMPUS?",
    description: "Geometry, Distance and Measurement, and Coordinate Geometry",
  },
  {
    id: "E",
    name: "WHO IS THE POKER GUY HERE",
    description: "Probability, Combinatorics, Game Theory, and Derangements",
  },
  {
    id: "F",
    name: "ASK OUT YOUR CRUSH",
    description: "PROBABILITY AND STATISTICS",
  },
  {
    id: "G",
    name: "I WANT A STRAIGHT TRAJECTORY IN LIFE",
    description: "Linear Systems, Geometry, Infinite Products, and Integrals",
  },
  {
    id: "H",
    name: "IS THE GUARD CHASING YOU?",
    description: "Coordinate Geometry, Conics, Vectors, and Relative Motion",
  },
  {
    id: "I",
    name: "WHAT AMOUNT TO PUT IN PAY REQUEST TO MY SENIORS",
    description: "Probability, Optimization, Geometric Distributions, and Game Theory",
  },
  {
    id: "J",
    name: "DO YOU HATE PROVING YOURSELF?",
    description: "Mathematical proofs, logic, induction, and contradiction",
  },
] as const;

export const OFFICIAL_RULES = [
  "Every team will start with 500 coins. These coins can be spent on buying themes, purchasing additional time, and buying hints for questions. Spend them wisely.",
  "Once a team proceeds to a question, the timer starts and will not stop during active solving. Each question has a base time limit of 4 minutes. Teams may purchase additional time using their coins. If the time runs out on a question, that theme is considered exhausted.",
  "A team cannot proceed to question X+1 without solving question X. No skipping ahead.",
  "Teams must submit their answer along with a text explanation. We very well know how to identify AI-generated texts, so make sure your explanation genuinely reflects your own reasoning. After submission, wait for approval from your respective admin. During this phase, the timer is paused. If the solution is rejected, the timer resumes. If it is approved, you may move on to the next question.",
  "There are 10 themes to choose from. The topics covered by each theme will be displayed before you buy it. Make optimal choices based on your strengths, available coins, and time.",
  "Use your own brain rather than AI or any other external means. If any team is found violating the rules, the admins have the authority to impose penalties, including decreasing the score—potentially to 0.",
  "Do not abuse or harass admins if they take time to approve your submissions. Admins are people too. You may, however, bribe your admin into approving your wrong solutions (highly recommended).",
  "Do not try to mess with the website or start playing with the spiral theme effect. Utilise your 4-hour time wisely.",
] as const;
