-- GENERATED by `npm run db:evidence` from supabase/migrations/*.sql. Do not edit by hand.
-- Reviewer copy of the schema (apply the migrations, not this file). Smoke checks: docs/evidence/schema-smoke.sql;
-- full tests: supabase/tests (npm run db:verify).

-- ===== 20261006000001_extensions_enums_clock.sql =====
-- Patch B / migration 1 of 9 — extensions, canonical enums, the app schema and the controllable clock.
-- Source: docs/DATA_MODEL.md §2, §3 (reconciled with the locked amendments; see docs/DATABASE_FOUNDATION.md).

create extension if not exists citext;
create extension if not exists pgcrypto;

-- Supabase already provides these roles. They are created only on a plain PostgreSQL (CI / local verification).
do $$ begin
  create role anon nologin;
exception when duplicate_object then null; end $$;
do $$ begin
  create role authenticated nologin;
exception when duplicate_object then null; end $$;
do $$ begin
  create role service_role nologin;
exception when duplicate_object then null; end $$;

-- Canonical state names (locked; do not rename).
create type competition_status as enum ('SETUP', 'RUNNING', 'PAUSED', 'ENDED');
create type team_status        as enum ('NOT_STARTED', 'RUNNING', 'FINAL_SUBMITTED', 'ENDED', 'DISQUALIFIED');
create type question_state     as enum ('LOCKED', 'AVAILABLE', 'ACTIVE', 'PENDING_APPROVAL', 'APPROVED', 'TIMED_OUT');
create type submission_status  as enum ('PENDING', 'APPROVED', 'REJECTED');
create type staff_role         as enum ('SUPER_ADMIN', 'ADMIN');          -- PARTICIPANT is not a staff role
create type session_kind       as enum ('STAFF', 'MEMBER');
create type presence_state     as enum ('OFFLINE', 'ONLINE');
create type difficulty         as enum ('EASY', 'MEDIUM', 'HARD');
create type coin_tx_type       as enum ('INITIAL_GRANT', 'THEME_UNLOCK', 'HINT_PURCHASE',
                                        'TIME_PURCHASE', 'QUESTION_REWARD', 'ADMIN_ADJUSTMENT');

create schema if not exists app;

-- The single time source for every competition rule. In production it is clock_timestamp();
-- tests may switch the clock with `set app.allow_test_clock = 'on'; set app.test_now = '...'`.
create function app.now() returns timestamptz language sql stable as $$
  select case
    when current_setting('app.allow_test_clock', true) = 'on'
     and nullif(current_setting('app.test_now', true), '') is not null
    then current_setting('app.test_now')::timestamptz
    else clock_timestamp()
  end
$$;

create function app.touch_updated_at() returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

-- ===== 20261006000002_competition_and_staff.sql =====
-- Patch B / migration 2 of 9 — the single competition row and staff accounts.

create table competition (
  id                          smallint primary key default 1 check (id = 1),
  status                      competition_status not null default 'SETUP',
  -- LOCKED: the Ultimate Team Timer is 2 hours = 7,200 s = 120 min (supersedes the Phase 0 value).
  ultimate_seconds            int  not null default 7200,
  ultimate_minutes            int  generated always as (ultimate_seconds / 60) stored,
  initial_coins               int  not null default 500,
  points_per_completed_theme  int  not null default 500,
  points_per_solved_question  int  not null default 100,
  penalty_per_minute          int  not null default 5,
  -- UFM (locked): a reset-adjusted score never goes below reset_floor_score; a disqualified team is pinned one below it.
  reset_floor_score           int  not null default -1200,
  disqualified_score          int  not null default -1201,
  opened_at                   timestamptz,                   -- SETUP -> RUNNING
  paused_at                   timestamptz,                   -- set while PAUSED
  ended_at                    timestamptz,
  state_version               bigint not null default 0,
  created_at                  timestamptz not null default now(),
  updated_at                  timestamptz not null default now(),
  constraint competition_ultimate_locked_7200 check (ultimate_seconds = 7200),
  constraint competition_initial_coins_nonneg check (initial_coins >= 0),
  constraint competition_ufm_floor_locked     check (reset_floor_score = -1200 and disqualified_score = reset_floor_score - 1),
  constraint competition_paused_has_timestamp check ((status = 'PAUSED') = (paused_at is not null)),
  constraint competition_ended_has_timestamp  check ((status = 'ENDED') = (ended_at is not null))
);
create trigger competition_touch before update on competition
  for each row execute function app.touch_updated_at();

create table staff_users (
  id            uuid primary key default gen_random_uuid(),
  username      citext not null unique,
  display_name  text   not null,
  password_hash text   not null,                 -- argon2id (or bcrypt fallback); never a plaintext password
  role          staff_role not null,
  is_active     boolean not null default true,
  created_by    uuid references staff_users(id) on delete restrict,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  last_login_at timestamptz,
  -- the Super Admin is provisioned out of band; every ADMIN is created by (and traceable to) a staff member
  constraint staff_admin_has_creator check (role = 'SUPER_ADMIN' or created_by is not null)
);
-- exactly one Super Admin can ever exist
create unique index staff_one_super_admin on staff_users ((role)) where role = 'SUPER_ADMIN';
create trigger staff_users_touch before update on staff_users
  for each row execute function app.touch_updated_at();

-- ===== 20261006000003_teams_members_sessions.sql =====
-- Patch B / migration 3 of 9 — teams, members (slots M1–M4) and sessions.

create table teams (
  id                     uuid primary key default gen_random_uuid(),
  team_code              text   not null unique,        -- "Team ID" in the brief, e.g. T17
  name                   text   not null,
  login_id               citext not null unique,        -- "Team Login ID"
  password_hash          text   not null,
  admin_id               uuid   not null references staff_users(id) on delete restrict,   -- the assigned admin
  status                 team_status not null default 'NOT_STARTED',
  coins                  int    not null check (coins >= 0),   -- authoritative balance; every change has a ledger row
  started_at             timestamptz,                    -- Ultimate Team Timer start (first member enters the competition)
  ends_at                timestamptz,                    -- started_at + ultimate_seconds (+ pause shifts)
  ended_at               timestamptz,                    -- set on FINAL_SUBMITTED / ENDED / DISQUALIFIED
  final_submitted_at     timestamptz,
  final_submitted_by     uuid,                           -- team_members.id (FK added below)
  score_override         int,                            -- Disqualify only: -1201; wins over every computed score
  score_reset_at         timestamptz,                    -- last UFM Reset; NULL if never reset
  score_reset_baseline   int,                            -- raw score at that instant; official = max(-1200, raw - baseline)
  final_score            int,                            -- cache, see compute_team_score()
  final_completed_themes int,
  final_solved_questions int,
  final_minutes_taken    int check (final_minutes_taken is null or final_minutes_taken between 0 and 120),
  state_version          bigint not null default 0,      -- bumped by every team-affecting transaction
  created_by             uuid references staff_users(id) on delete restrict,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  constraint teams_started_iff_not_not_started check ((status = 'NOT_STARTED') = (started_at is null)),
  constraint teams_ends_after_start             check (ends_at is null or ends_at > started_at),
  constraint teams_reset_columns_paired         check ((score_reset_at is null) = (score_reset_baseline is null)),
  -- UFM: only a disqualification pins the score, and it pins it to exactly -1201 (competition.disqualified_score)
  constraint teams_disqualified_score           check ((status = 'DISQUALIFIED') = (score_override is not null)
                                                       and (score_override is null or score_override = -1201)),
  constraint teams_final_submit_columns         check ((status = 'FINAL_SUBMITTED') = (final_submitted_at is not null)),
  constraint teams_terminal_has_ended_at        check ((status in ('FINAL_SUBMITTED', 'ENDED', 'DISQUALIFIED')) = (ended_at is not null))
);
create index teams_admin_idx  on teams (admin_id);
create index teams_status_idx on teams (status);
create index teams_due_idx    on teams (ends_at) where status = 'RUNNING';   -- expiry sweeper
create trigger teams_touch before update on teams
  for each row execute function app.touch_updated_at();

create table team_members (
  id            uuid primary key default gen_random_uuid(),
  team_id       uuid not null references teams(id) on delete restrict,
  slot          smallint not null check (slot between 1 and 4),   -- M1..M4
  admission_no  text not null unique,                    -- globally unique across all teams (normalised by the app)
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (team_id, slot),
  unique (id, team_id),                                  -- lets other tables prove "this member belongs to this team"
  constraint team_members_admission_normalised check (admission_no = upper(btrim(admission_no)) and admission_no <> '')
);
create trigger team_members_touch before update on team_members
  for each row execute function app.touch_updated_at();

-- the member who final-submitted must belong to this very team
alter table teams
  add constraint teams_final_submitted_by_fk foreign key (final_submitted_by, id) references team_members(id, team_id) on delete restrict;

-- One table for every login session (decision A2). member_sessions / admin_sessions / team_sessions below are read-only views.
create table sessions (
  id             uuid primary key default gen_random_uuid(),
  token_hash     bytea not null unique,                  -- sha256 of the cookie value; the token itself is never stored
  kind           session_kind not null,
  staff_id       uuid references staff_users(id) on delete restrict,
  team_id        uuid references teams(id) on delete restrict,
  member_id      uuid references team_members(id) on delete restrict,
  created_at     timestamptz not null default now(),
  last_seen_at   timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  expires_at     timestamptz not null,
  revoked_at     timestamptz,
  revoke_reason  text check (revoke_reason in ('LOGOUT', 'SUPERSEDED', 'FULLSCREEN_EXIT', 'ADMIN_DISABLED', 'EXPIRED')),
  ip             inet,
  user_agent     text,
  constraint sessions_principal check (
        (kind = 'STAFF'  and staff_id is not null and member_id is null and team_id is null)
     or (kind = 'MEMBER' and member_id is not null and team_id is not null and staff_id is null)),
  constraint sessions_member_belongs_to_team foreign key (member_id, team_id) references team_members(id, team_id),
  constraint sessions_expiry_after_creation check (expires_at > created_at),
  constraint sessions_revoke_pair check ((revoked_at is null) = (revoke_reason is null))
);
-- at most one live session per member; a new login revokes the old one in the same transaction
create unique index sessions_one_live_member on sessions (member_id) where kind = 'MEMBER' and revoked_at is null;
create index sessions_team_idx  on sessions (team_id)  where revoked_at is null;
create index sessions_staff_idx on sessions (staff_id) where revoked_at is null;
create trigger sessions_touch before update on sessions
  for each row execute function app.touch_updated_at();

-- Read-only role-shaped views over the sessions table (no data is duplicated).
create view member_sessions with (security_invoker = true) as
select s.id, s.team_id, s.member_id, m.slot as member_slot, s.created_at, s.last_seen_at, s.expires_at,
       s.revoked_at, s.revoke_reason, (s.revoked_at is null and s.expires_at > app.now()) as is_live
from sessions s join team_members m on m.id = s.member_id
where s.kind = 'MEMBER';

create view admin_sessions with (security_invoker = true) as
select s.id, s.staff_id, u.role as staff_role, s.created_at, s.last_seen_at, s.expires_at,
       s.revoked_at, s.revoke_reason, (s.revoked_at is null and s.expires_at > app.now()) as is_live
from sessions s join staff_users u on u.id = s.staff_id
where s.kind = 'STAFF';

-- Team-level competition run state (the authoritative Ultimate Team Timer lives on `teams`).
create view team_sessions with (security_invoker = true) as
select t.id as team_id, t.status, t.started_at, t.ends_at, t.ended_at, t.final_submitted_at, t.final_submitted_by,
       t.state_version
from teams t;

-- ===== 20261006000004_content.sql =====
-- Patch B / migration 4 of 9 — competition content: 10 themes (A–J) × 5 questions = 50 questions, hints, reviewer keys.
-- Content is seeded (supabase/seed.sql) and read-only at runtime. There are NO themes K or L.

create table themes (
  id            smallint primary key check (id between 1 and 10),
  code          char(1) not null unique check (code between 'A' and 'J'),   -- 'A'..'J' (admin matrix columns)
  name          text not null,
  description   text not null,
  topics        text[] not null default '{}',
  difficulty    difficulty not null,
  unlock_cost   int not null check (unlock_cost >= 0),          -- configurable content data, not a code constant
  display_order smallint not null unique,
  -- the code is the id'th letter of the alphabet: 1 = A ... 10 = J
  constraint themes_code_matches_id check (code = chr(64 + id))
);

create table questions (
  id                  smallint primary key check (id between 1 and 50),
  theme_id            smallint not null references themes(id) on delete restrict,
  ordinal             smallint not null check (ordinal between 1 and 5),
  body_md             text not null,                            -- Markdown + KaTeX (decision DEC-15)
  difficulty          difficulty not null,
  reward_coins        int not null check (reward_coins >= 0),   -- fixed per question; an admin never chooses it
  time_limit_seconds  int not null check (time_limit_seconds > 0),   -- the per-question timer (4:00 in the seed)
  buy_time_seconds    int not null check (buy_time_seconds > 0),
  buy_time_cost       int not null check (buy_time_cost >= 0),
  max_time_purchases  int check (max_time_purchases is null or max_time_purchases >= 0),   -- null = unlimited
  unique (theme_id, ordinal),
  unique (id, theme_id),                                         -- lets progress tables prove question ↔ theme agreement
  constraint questions_id_matches_position check (id = (theme_id - 1) * 5 + ordinal)
);

-- reviewer-only material, kept in a separate table so it can never ride along in a participant query
create table question_keys (
  question_id       smallint primary key references questions(id) on delete restrict,
  reference_answer  text not null,
  solution_notes    text
);

create table hints (
  id           smallint primary key check (id between 1 and 100),
  question_id  smallint not null references questions(id) on delete restrict,
  tier         smallint not null check (tier in (1, 2)),
  body_md      text not null,
  cost         int not null check (cost >= 0),                  -- configurable content data
  unique (question_id, tier),
  unique (id, question_id)
);

-- ===== 20261006000005_team_progress.sql =====
-- Patch B / migration 5 of 9 — per-team progress: unlocked themes, question states and timers, drafts, hints.

create table team_themes (               -- a row exists iff the theme is unlocked
  team_id      uuid not null references teams(id) on delete restrict,
  theme_id     smallint not null references themes(id) on delete restrict,
  unlocked_by  uuid not null,
  unlocked_at  timestamptz not null,
  cost_paid    int not null check (cost_paid >= 0),
  primary key (team_id, theme_id),
  constraint team_themes_member_in_team foreign key (unlocked_by, team_id) references team_members(id, team_id) on delete restrict
);

-- 5 rows are created when a theme is unlocked: Q1 AVAILABLE (no timer until a participant enters it → start_question),
-- Q2..Q5 LOCKED. A question timer starts when the question becomes ACTIVE — never at theme unlock.
create table team_questions (
  team_id                 uuid not null references teams(id) on delete restrict,
  question_id             smallint not null,
  theme_id                smallint not null,                    -- denormalised for indexes; kept consistent by the FK below
  ordinal                 smallint not null check (ordinal between 1 and 5),
  state                   question_state not null default 'LOCKED',
  timer_deadline          timestamptz,            -- set iff ACTIVE (authoritative, shared by all members)
  timer_remaining_seconds int,                    -- set iff PENDING_APPROVAL (timer frozen while approval is pending)
  extra_seconds           int not null default 0 check (extra_seconds >= 0),   -- total purchased, informational
  time_purchase_count     int not null default 0 check (time_purchase_count >= 0),
  activated_at            timestamptz,            -- set when the question becomes ACTIVE (the timer start)
  approved_at             timestamptz,
  timed_out_at            timestamptz,
  primary key (team_id, question_id),
  constraint team_questions_question_fk foreign key (question_id, theme_id) references questions(id, theme_id) on delete restrict,
  constraint team_questions_theme_unlocked_fk foreign key (team_id, theme_id) references team_themes(team_id, theme_id) on delete restrict,
  constraint team_questions_active_has_deadline   check ((state = 'ACTIVE') = (timer_deadline is not null)),
  constraint team_questions_pending_has_remaining check ((state = 'PENDING_APPROVAL') = (timer_remaining_seconds is not null)),
  constraint team_questions_remaining_nonneg      check (timer_remaining_seconds is null or timer_remaining_seconds >= 0),
  -- LOCKED and AVAILABLE questions have never been started: no timer start is recorded
  constraint team_questions_unstarted_no_activation check ((state in ('LOCKED', 'AVAILABLE')) = (activated_at is null)),
  -- INV-04: only Q1 is ever AVAILABLE (Q2..Q5 go LOCKED -> ACTIVE when the previous question is approved)
  constraint team_questions_available_only_q1 check (state <> 'AVAILABLE' or ordinal = 1),
  constraint team_questions_approved_at  check ((state = 'APPROVED')  = (approved_at is not null)),
  constraint team_questions_timed_out_at check ((state = 'TIMED_OUT') = (timed_out_at is not null))
);
create index tq_team_state_idx on team_questions (team_id, state);
create index tq_due_idx        on team_questions (timer_deadline) where state = 'ACTIVE';   -- timeout sweeper

-- QN+1 cannot become ACTIVE / PENDING_APPROVAL / APPROVED / TIMED_OUT until QN is APPROVED (database-level guard).
create function app.question_order_guard() returns trigger language plpgsql as $$
begin
  if new.ordinal > 1
     and new.state in ('ACTIVE', 'PENDING_APPROVAL', 'APPROVED', 'TIMED_OUT')
     and not exists (select 1 from team_questions p
                      where p.team_id = new.team_id and p.theme_id = new.theme_id
                        and p.ordinal = new.ordinal - 1 and p.state = 'APPROVED') then
    raise exception 'QUESTION_PREVIOUS_NOT_APPROVED' using errcode = 'P0001';
  end if;
  return new;
end $$;
create trigger team_questions_order before insert or update of state on team_questions
  for each row execute function app.question_order_guard();

create table answer_drafts (             -- one shared draft per team+question; KEPT after a rejection (locked UI-2.1 rule)
  team_id      uuid not null references teams(id) on delete restrict,
  question_id  smallint not null references questions(id) on delete restrict,
  answer       text not null default '',
  explanation  text not null default '',
  version      int  not null default 0,  -- optimistic concurrency (see API_SPEC saveDraft)
  updated_by   uuid,
  updated_at   timestamptz not null default now(),
  primary key (team_id, question_id),
  constraint answer_drafts_length check (length(answer) <= 10000 and length(explanation) <= 10000),
  constraint answer_drafts_member_in_team foreign key (updated_by, team_id) references team_members(id, team_id) on delete restrict
);

create table hint_purchases (
  team_id       uuid not null references teams(id) on delete restrict,
  hint_id       smallint not null references hints(id) on delete restrict,
  purchased_by  uuid not null,
  cost_paid     int not null check (cost_paid >= 0),
  purchased_at  timestamptz not null,
  primary key (team_id, hint_id),        -- a team can never pay twice for the same hint
  constraint hint_purchases_member_in_team foreign key (purchased_by, team_id) references team_members(id, team_id) on delete restrict
);

-- Tier 2 requires Tier 1 of the same question (second guard; buy_hint will check first, under the team lock)
create function app.hint_tier_order() returns trigger language plpgsql as $$
begin
  if (select tier from hints where id = new.hint_id) = 2
     and not exists (select 1
                       from hint_purchases p
                       join hints h1 on h1.id = p.hint_id and h1.tier = 1
                      where p.team_id = new.team_id
                        and h1.question_id = (select question_id from hints where id = new.hint_id)) then
    raise exception 'HINT_TIER1_REQUIRED' using errcode = 'P0001';
  end if;
  return new;
end $$;
create trigger hint_purchases_tier_order before insert on hint_purchases
  for each row execute function app.hint_tier_order();

-- ===== 20261006000006_submissions_and_coins.sql =====
-- Patch B / migration 6 of 9 — submissions (full history) and the immutable coin ledger.

create table submissions (
  id            uuid primary key default gen_random_uuid(),
  team_id       uuid not null references teams(id) on delete restrict,
  question_id   smallint not null references questions(id) on delete restrict,
  member_id     uuid not null,                         -- the member (M1–M4) who pressed Submit
  answer        text not null check (length(answer) between 1 and 10000),
  explanation   text not null check (length(explanation) <= 10000),
  status        submission_status not null default 'PENDING',
  submitted_at  timestamptz not null,
  reviewed_by   uuid references staff_users(id) on delete restrict,
  reviewed_at   timestamptz,
  review_note   text,                    -- optional reviewer note shown to the team
  reward_awarded int check (reward_awarded is null or reward_awarded >= 0),
  created_at    timestamptz not null default now(),
  constraint submissions_member_in_team foreign key (member_id, team_id) references team_members(id, team_id) on delete restrict,
  constraint submissions_reviewed_iff_decided check ((status = 'PENDING') = (reviewed_at is null)),
  constraint submissions_decided_has_reviewer check (status = 'PENDING' or reviewed_by is not null),
  constraint submissions_reward_only_if_approved check (reward_awarded is null or status = 'APPROVED')
);
-- only ONE pending submission per team+question, enforced by the database; REJECTED rows stay forever (auditable)
create unique index submissions_one_pending on submissions (team_id, question_id) where status = 'PENDING';
create index submissions_queue_idx on submissions (submitted_at) where status = 'PENDING';
create index submissions_team_idx  on submissions (team_id, question_id, submitted_at);
create index submissions_member_idx on submissions (member_id);

-- Immutable ledger. teams.coins is the authoritative balance; the ledger explains every change to it.
create table coin_transactions (
  id              bigserial primary key,
  team_id         uuid not null references teams(id) on delete restrict,
  type            coin_tx_type not null,
  amount          int  not null check (amount <> 0),               -- signed: spends negative, rewards positive
  balance_after   int  not null check (balance_after >= 0),
  theme_id        smallint references themes(id) on delete restrict,
  hint_id         smallint references hints(id) on delete restrict,
  question_id     smallint references questions(id) on delete restrict,
  submission_id   uuid     references submissions(id) on delete restrict,
  purchase_seq    int,                           -- TIME_PURCHASE: team_questions.time_purchase_count after the buy
  member_id       uuid,
  staff_id        uuid references staff_users(id) on delete restrict,
  created_at      timestamptz not null,
  constraint coin_tx_member_in_team foreign key (member_id, team_id) references team_members(id, team_id) on delete restrict,
  constraint coin_tx_sign check (
        (type in ('THEME_UNLOCK', 'HINT_PURCHASE', 'TIME_PURCHASE') and amount < 0)
     or (type in ('INITIAL_GRANT', 'QUESTION_REWARD') and amount > 0)
     or type = 'ADMIN_ADJUSTMENT'),
  -- each spend/reward names the thing it is for, so it can be made idempotent below
  constraint coin_tx_subject check (
        (type = 'THEME_UNLOCK'    and theme_id is not null)
     or (type = 'HINT_PURCHASE'   and hint_id is not null)
     or (type = 'TIME_PURCHASE'   and question_id is not null and purchase_seq is not null)
     or (type = 'QUESTION_REWARD' and question_id is not null)
     or (type = 'ADMIN_ADJUSTMENT' and staff_id is not null)
     or (type = 'INITIAL_GRANT')),
  constraint coin_tx_purchase_seq_positive check (purchase_seq is null or purchase_seq >= 1)
);
-- "cannot happen twice" guarantees, enforced at the ledger level (no duplicate grant, deduction or reward)
create unique index ctx_initial    on coin_transactions (team_id)                            where type = 'INITIAL_GRANT';
create unique index ctx_theme      on coin_transactions (team_id, theme_id)                  where type = 'THEME_UNLOCK';
create unique index ctx_hint       on coin_transactions (team_id, hint_id)                   where type = 'HINT_PURCHASE';
create unique index ctx_reward     on coin_transactions (team_id, question_id)               where type = 'QUESTION_REWARD';
create unique index ctx_time       on coin_transactions (team_id, question_id, purchase_seq) where type = 'TIME_PURCHASE';
create index ctx_team_idx          on coin_transactions (team_id, id);

-- Append-only: ledger rows are never updated, deleted or truncated (corrections are new ADMIN_ADJUSTMENT rows).
create function app.ledger_immutable() returns trigger language plpgsql as $$
begin raise exception 'coin_transactions is append-only'; end $$;
create trigger coin_tx_no_update before update or delete on coin_transactions
  for each row execute function app.ledger_immutable();
create trigger coin_tx_no_truncate before truncate on coin_transactions
  for each statement execute function app.ledger_immutable();

-- Running-balance chain: balance_after must equal the previous balance + amount (0 before the first row), and the
-- INITIAL_GRANT must equal competition.initial_coins. Concurrent inserts for one team serialise on the team row lock.
create function app.ledger_balance_chain() returns trigger language plpgsql as $$
declare prev int;
begin
  perform 1 from teams where id = new.team_id for update;
  select balance_after into prev from coin_transactions where team_id = new.team_id order by id desc limit 1;
  prev := coalesce(prev, 0);
  if new.balance_after <> prev + new.amount then
    raise exception 'LEDGER_BALANCE_MISMATCH: balance_after % <> % + %', new.balance_after, prev, new.amount
      using errcode = 'P0001';
  end if;
  if new.type = 'INITIAL_GRANT' and new.amount <> (select initial_coins from competition where id = 1) then
    raise exception 'LEDGER_INITIAL_GRANT_MISMATCH' using errcode = 'P0001';
  end if;
  return new;
end $$;
create trigger coin_tx_balance_chain before insert on coin_transactions
  for each row execute function app.ledger_balance_chain();

-- ===== 20261006000007_audit_and_support.sql =====
-- Patch B / migration 7 of 9 — idempotency log, append-only audit trail and supporting tables.

create table request_log (
  team_id       uuid not null,                   -- or the staff id for staff operations
  idem_key      uuid not null,                   -- client-generated Idempotency-Key
  operation     text not null,
  response      jsonb not null,
  created_at    timestamptz not null default now(),
  primary key (team_id, idem_key)
);
create index request_log_created_idx on request_log (created_at);   -- hourly purge

-- Event types are catalogued in docs/STATE_MACHINE.md §8 (kept as text so the catalogue can grow without a migration).
create table audit_events (
  id              bigserial primary key,
  occurred_at     timestamptz not null default now(),
  actor_kind      text not null check (actor_kind in ('STAFF', 'MEMBER', 'SYSTEM')),
  staff_id        uuid,
  member_id       uuid,
  team_id         uuid,
  event_type      text not null check (event_type <> ''),
  entity_type     text,
  entity_id       text,
  payload         jsonb not null default '{}',   -- before/after values, amounts, reasons
  request_id      uuid,
  ip              inet,
  constraint audit_actor_matches_kind check (
        (actor_kind = 'STAFF'  and staff_id is not null)
     or (actor_kind = 'MEMBER' and member_id is not null)
     or (actor_kind = 'SYSTEM'))
);
create index audit_team_idx on audit_events (team_id, id);
create index audit_type_idx on audit_events (event_type, id);

create function app.audit_immutable() returns trigger language plpgsql as $$
begin raise exception 'audit_events is append-only'; end $$;
create trigger audit_no_update before update or delete on audit_events
  for each row execute function app.audit_immutable();
create trigger audit_no_truncate before truncate on audit_events
  for each statement execute function app.audit_immutable();
revoke update, delete, truncate on audit_events from public, anon, authenticated, service_role;

create table leaderboard_snapshot (      -- single row, refreshed at most every 60 s
  id           smallint primary key default 1 check (id = 1),
  computed_at  timestamptz not null,
  rows         jsonb not null              -- [{rank, team_id, team_name, score, status}]
);

create table auth_throttle (             -- login rate limiting; keyed per account, NOT per IP
  key           text primary key,        -- 'team:<login_id>' | 'staff:<username>'
  window_start  timestamptz not null,
  attempts      int not null check (attempts >= 0),
  locked_until  timestamptz
);

create table ufm_challenges (            -- server-side second step for destructive admin actions (two-step confirmation)
  id          uuid primary key default gen_random_uuid(),
  staff_id    uuid not null references staff_users(id) on delete restrict,
  team_id     uuid not null references teams(id) on delete restrict,
  action      text not null check (action in ('RESET_SCORE', 'DISQUALIFY')),
  expires_at  timestamptz not null,
  used_at     timestamptz,
  created_at  timestamptz not null default now()
);
create index ufm_challenges_team_idx on ufm_challenges (team_id);

-- ===== 20261006000008_views_and_invariants.sql =====
-- Patch B / migration 8 of 9 — derived views and read-only invariant checkers (no game logic).

-- progress per team+theme (5 = QUESTIONS_PER_THEME)
create view team_theme_progress with (security_invoker = true) as
select team_id, theme_id,
       count(*) filter (where state = 'APPROVED') as approved_count,
       coalesce(bool_or(state = 'TIMED_OUT'), false) as has_timed_out,
       count(*) filter (where state = 'APPROVED') = 5 as completed
from team_questions group by team_id, theme_id;

-- presence: OFFLINE / ONLINE (a member is ONLINE while a live session has been seen in the last 75 s)
create view member_presence with (security_invoker = true) as
select m.id as member_id, m.team_id, m.slot,
       (case when exists (select 1 from sessions s
                           where s.member_id = m.id and s.revoked_at is null
                             and s.last_seen_at > app.now() - interval '75 seconds')
             then 'ONLINE' else 'OFFLINE' end)::presence_state as presence
from team_members m;

-- Invariant checkers: each returns the offending rows and must be empty at all times.
create view app.invariant_coin_balance_mismatch as          -- INV: teams.coins = last ledger balance_after
select t.id as team_id, t.coins, coalesce(l.balance_after, 0) as ledger_balance
from teams t
left join lateral (select balance_after from coin_transactions c where c.team_id = t.id order by c.id desc limit 1) l on true
where t.coins <> coalesce(l.balance_after, 0);

create view app.invariant_team_member_count as              -- INV: 1..4 members per team once the team exists
select t.id as team_id, count(m.id) as members
from teams t left join team_members m on m.team_id = t.id
group by t.id having count(m.id) not between 1 and 4;

-- ===== 20261006000009_security_rls.sql =====
-- Patch B / migration 9 of 9 — security foundation (decision A2/A3, docs/SECURITY.md SEC-06).
--
-- Model: the browser holds no database credentials that can read or write anything. Every table has row level
-- security ENABLED and FORCED and there are NO policies for anon/authenticated, so the Supabase anon/authenticated
-- keys can see nothing. All access goes through server code using the service role (never exposed to the browser),
-- and, from Phase 5, through SECURITY DEFINER engine functions that check ownership server-side:
--   PARTICIPANT → only their own team (session.team_id), ADMIN → only teams with teams.admin_id = their id,
--   SUPER_ADMIN → everything. Ownership is therefore enforced by the server, never by the client.

do $$
declare t record;
begin
  for t in select c.relname from pg_class c join pg_namespace n on n.oid = c.relnamespace
            where n.nspname = 'public' and c.relkind = 'r' loop
    execute format('alter table public.%I enable row level security', t.relname);
    execute format('alter table public.%I force row level security', t.relname);
  end loop;
end $$;

-- No default exposure through the Supabase Data API: remove every grant from the browser-facing roles.
revoke all on all tables    in schema public from public, anon, authenticated;
revoke all on all sequences in schema public from public, anon, authenticated;
revoke all on all functions in schema public from public, anon, authenticated;
alter default privileges in schema public revoke all on tables    from anon, authenticated;
alter default privileges in schema public revoke all on sequences from anon, authenticated;
alter default privileges in schema public revoke all on functions from anon, authenticated;

revoke all on schema app from public, anon, authenticated;
revoke all on all tables    in schema app from public, anon, authenticated;
revoke all on all functions in schema app from public, anon, authenticated;

-- The server (service role) works through explicit grants. The audit trail and the coin ledger stay append-only.
grant usage on schema public, app to service_role;
grant select, insert, update, delete on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;
grant select on all tables in schema app to service_role;
grant execute on all functions in schema app to service_role;
revoke update, delete, truncate on audit_events      from service_role;
revoke update, delete, truncate on coin_transactions from service_role;
