-- GENERATED by `npm run db:evidence` from supabase/migrations/*.sql. Do not edit by hand.
-- Reviewer copy of the schema (apply the migrations, not this file). Smoke checks: docs/evidence/schema-smoke.sql;
-- full tests: supabase/tests (npm run db:verify).

-- ===== 20261006000001_extensions_enums_clock.sql =====
-- Patch B / migration 1 of 9 — extensions, canonical enums, the app schema and the controllable clock.
-- Source: docs/DATA_MODEL.md §2, §3 (reconciled with the locked amendments; see docs/DATABASE_FOUNDATION.md).

create extension if not exists citext;
create extension if not exists pgcrypto;

-- Supabase already provides these roles. They are created only on a plain PostgreSQL (CI / local verification).
do $$ begin
  create role anon nologin;
exception when duplicate_object then null; end $$;
do $$ begin
  create role authenticated nologin;
exception when duplicate_object then null; end $$;
do $$ begin
  create role service_role nologin;
exception when duplicate_object then null; end $$;

-- Canonical state names (locked; do not rename).
create type competition_status as enum ('SETUP', 'RUNNING', 'PAUSED', 'ENDED');
create type team_status        as enum ('NOT_STARTED', 'RUNNING', 'FINAL_SUBMITTED', 'ENDED', 'DISQUALIFIED');
create type question_state     as enum ('LOCKED', 'AVAILABLE', 'ACTIVE', 'PENDING_APPROVAL', 'APPROVED', 'TIMED_OUT');
create type submission_status  as enum ('PENDING', 'APPROVED', 'REJECTED');
create type staff_role         as enum ('SUPER_ADMIN', 'ADMIN');          -- PARTICIPANT is not a staff role
create type session_kind       as enum ('STAFF', 'MEMBER');
create type presence_state     as enum ('OFFLINE', 'ONLINE');
create type difficulty         as enum ('EASY', 'MEDIUM', 'HARD');
create type coin_tx_type       as enum ('INITIAL_GRANT', 'THEME_UNLOCK', 'HINT_PURCHASE',
                                        'TIME_PURCHASE', 'QUESTION_REWARD', 'ADMIN_ADJUSTMENT');

create schema if not exists app;

-- The single time source for every competition rule. In production it is clock_timestamp();
-- tests may switch the clock with `set app.allow_test_clock = 'on'; set app.test_now = '...'`.
create function app.now() returns timestamptz language sql stable as $$
  select case
    when current_setting('app.allow_test_clock', true) = 'on'
     and nullif(current_setting('app.test_now', true), '') is not null
    then current_setting('app.test_now')::timestamptz
    else clock_timestamp()
  end
$$;

create function app.touch_updated_at() returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

-- ===== 20261006000002_competition_and_staff.sql =====
-- Patch B / migration 2 of 9 — the single competition row and staff accounts.

create table competition (
  id                          smallint primary key default 1 check (id = 1),
  status                      competition_status not null default 'SETUP',
  -- LOCKED: the Ultimate Team Timer is 2 hours = 7,200 s = 120 min (supersedes the Phase 0 value).
  ultimate_seconds            int  not null default 7200,
  ultimate_minutes            int  generated always as (ultimate_seconds / 60) stored,
  initial_coins               int  not null default 500,
  points_per_completed_theme  int  not null default 500,
  points_per_solved_question  int  not null default 100,
  penalty_per_minute          int  not null default 5,
  -- UFM (locked): a reset-adjusted score never goes below reset_floor_score; a disqualified team is pinned one below it.
  reset_floor_score           int  not null default -1200,
  disqualified_score          int  not null default -1201,
  opened_at                   timestamptz,                   -- SETUP -> RUNNING
  paused_at                   timestamptz,                   -- set while PAUSED
  ended_at                    timestamptz,
  state_version               bigint not null default 0,
  created_at                  timestamptz not null default now(),
  updated_at                  timestamptz not null default now(),
  constraint competition_ultimate_locked_7200 check (ultimate_seconds = 7200),
  constraint competition_initial_coins_nonneg check (initial_coins >= 0),
  constraint competition_ufm_floor_locked     check (reset_floor_score = -1200 and disqualified_score = reset_floor_score - 1),
  constraint competition_paused_has_timestamp check ((status = 'PAUSED') = (paused_at is not null)),
  constraint competition_ended_has_timestamp  check ((status = 'ENDED') = (ended_at is not null))
);
create trigger competition_touch before update on competition
  for each row execute function app.touch_updated_at();

create table staff_users (
  id            uuid primary key default gen_random_uuid(),
  username      citext not null unique,
  display_name  text   not null,
  password_hash text   not null,                 -- argon2id (or bcrypt fallback); never a plaintext password
  role          staff_role not null,
  is_active     boolean not null default true,
  created_by    uuid references staff_users(id) on delete restrict,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  last_login_at timestamptz,
  -- the Super Admin is provisioned out of band; every ADMIN is created by (and traceable to) a staff member
  constraint staff_admin_has_creator check (role = 'SUPER_ADMIN' or created_by is not null)
);
-- exactly one Super Admin can ever exist
create unique index staff_one_super_admin on staff_users ((role)) where role = 'SUPER_ADMIN';
create trigger staff_users_touch before update on staff_users
  for each row execute function app.touch_updated_at();

-- ===== 20261006000003_teams_members_sessions.sql =====
-- Patch B / migration 3 of 9 — teams, members (slots M1–M4) and sessions.

create table teams (
  id                     uuid primary key default gen_random_uuid(),
  team_code              text   not null unique,        -- "Team ID" in the brief, e.g. T17
  name                   text   not null,
  login_id               citext not null unique,        -- "Team Login ID"
  password_hash          text   not null,
  admin_id               uuid   not null references staff_users(id) on delete restrict,   -- the assigned admin
  status                 team_status not null default 'NOT_STARTED',
  coins                  int    not null check (coins >= 0),   -- authoritative balance; every change has a ledger row
  started_at             timestamptz,                    -- Ultimate Team Timer start (first member enters the competition)
  ends_at                timestamptz,                    -- started_at + ultimate_seconds (+ pause shifts)
  ended_at               timestamptz,                    -- set on FINAL_SUBMITTED / ENDED / DISQUALIFIED
  final_submitted_at     timestamptz,
  final_submitted_by     uuid,                           -- team_members.id (FK added below)
  score_override         int,                            -- Disqualify only: -1201; wins over every computed score
  score_reset_at         timestamptz,                    -- last UFM Reset; NULL if never reset
  score_reset_baseline   int,                            -- raw score at that instant; official = max(-1200, raw - baseline)
  final_score            int,                            -- cache, see compute_team_score()
  final_completed_themes int,
  final_solved_questions int,
  final_minutes_taken    int check (final_minutes_taken is null or final_minutes_taken between 0 and 120),
  state_version          bigint not null default 0,      -- bumped by every team-affecting transaction
  created_by             uuid references staff_users(id) on delete restrict,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  constraint teams_started_iff_not_not_started check ((status = 'NOT_STARTED') = (started_at is null)),
  constraint teams_ends_after_start             check (ends_at is null or ends_at > started_at),
  constraint teams_reset_columns_paired         check ((score_reset_at is null) = (score_reset_baseline is null)),
  -- UFM: only a disqualification pins the score, and it pins it to exactly -1201 (competition.disqualified_score)
  constraint teams_disqualified_score           check ((status = 'DISQUALIFIED') = (score_override is not null)
                                                       and (score_override is null or score_override = -1201)),
  constraint teams_final_submit_columns         check ((status = 'FINAL_SUBMITTED') = (final_submitted_at is not null)),
  constraint teams_terminal_has_ended_at        check ((status in ('FINAL_SUBMITTED', 'ENDED', 'DISQUALIFIED')) = (ended_at is not null))
);
create index teams_admin_idx  on teams (admin_id);
create index teams_status_idx on teams (status);
create index teams_due_idx    on teams (ends_at) where status = 'RUNNING';   -- expiry sweeper
create trigger teams_touch before update on teams
  for each row execute function app.touch_updated_at();

create table team_members (
  id            uuid primary key default gen_random_uuid(),
  team_id       uuid not null references teams(id) on delete restrict,
  slot          smallint not null check (slot between 1 and 4),   -- M1..M4
  admission_no  text not null unique,                    -- globally unique across all teams (normalised by the app)
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (team_id, slot),
  unique (id, team_id),                                  -- lets other tables prove "this member belongs to this team"
  constraint team_members_admission_normalised check (admission_no = upper(btrim(admission_no)) and admission_no <> '')
);
create trigger team_members_touch before update on team_members
  for each row execute function app.touch_updated_at();

-- the member who final-submitted must belong to this very team
alter table teams
  add constraint teams_final_submitted_by_fk foreign key (final_submitted_by, id) references team_members(id, team_id) on delete restrict;

-- One table for every login session (decision A2). member_sessions / admin_sessions / team_sessions below are read-only views.
create table sessions (
  id             uuid primary key default gen_random_uuid(),
  token_hash     bytea not null unique,                  -- sha256 of the cookie value; the token itself is never stored
  kind           session_kind not null,
  staff_id       uuid references staff_users(id) on delete restrict,
  team_id        uuid references teams(id) on delete restrict,
  member_id      uuid references team_members(id) on delete restrict,
  created_at     timestamptz not null default now(),
  last_seen_at   timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  expires_at     timestamptz not null,
  revoked_at     timestamptz,
  revoke_reason  text check (revoke_reason in ('LOGOUT', 'SUPERSEDED', 'FULLSCREEN_EXIT', 'ADMIN_DISABLED', 'EXPIRED')),
  ip             inet,
  user_agent     text,
  constraint sessions_principal check (
        (kind = 'STAFF'  and staff_id is not null and member_id is null and team_id is null)
     or (kind = 'MEMBER' and member_id is not null and team_id is not null and staff_id is null)),
  constraint sessions_member_belongs_to_team foreign key (member_id, team_id) references team_members(id, team_id),
  constraint sessions_expiry_after_creation check (expires_at > created_at),
  constraint sessions_revoke_pair check ((revoked_at is null) = (revoke_reason is null))
);
-- at most one live session per member; a new login revokes the old one in the same transaction
create unique index sessions_one_live_member on sessions (member_id) where kind = 'MEMBER' and revoked_at is null;
create index sessions_team_idx  on sessions (team_id)  where revoked_at is null;
create index sessions_staff_idx on sessions (staff_id) where revoked_at is null;
create trigger sessions_touch before update on sessions
  for each row execute function app.touch_updated_at();

-- Read-only role-shaped views over the sessions table (no data is duplicated).
create view member_sessions with (security_invoker = true) as
select s.id, s.team_id, s.member_id, m.slot as member_slot, s.created_at, s.last_seen_at, s.expires_at,
       s.revoked_at, s.revoke_reason, (s.revoked_at is null and s.expires_at > app.now()) as is_live
from sessions s join team_members m on m.id = s.member_id
where s.kind = 'MEMBER';

create view admin_sessions with (security_invoker = true) as
select s.id, s.staff_id, u.role as staff_role, s.created_at, s.last_seen_at, s.expires_at,
       s.revoked_at, s.revoke_reason, (s.revoked_at is null and s.expires_at > app.now()) as is_live
from sessions s join staff_users u on u.id = s.staff_id
where s.kind = 'STAFF';

-- Team-level competition run state (the authoritative Ultimate Team Timer lives on `teams`).
create view team_sessions with (security_invoker = true) as
select t.id as team_id, t.status, t.started_at, t.ends_at, t.ended_at, t.final_submitted_at, t.final_submitted_by,
       t.state_version
from teams t;

-- ===== 20261006000004_content.sql =====
-- Patch B / migration 4 of 9 — competition content: 10 themes (A–J) × 5 questions = 50 questions, hints, reviewer keys.
-- Content is seeded (supabase/seed.sql) and read-only at runtime. There are NO themes K or L.

create table themes (
  id            smallint primary key check (id between 1 and 10),
  code          char(1) not null unique check (code between 'A' and 'J'),   -- 'A'..'J' (admin matrix columns)
  name          text not null,
  description   text not null,
  topics        text[] not null default '{}',
  difficulty    difficulty not null,
  unlock_cost   int not null check (unlock_cost >= 0),          -- configurable content data, not a code constant
  display_order smallint not null unique,
  -- the code is the id'th letter of the alphabet: 1 = A ... 10 = J
  constraint themes_code_matches_id check (code = chr(64 + id))
);

create table questions (
  id                  smallint primary key check (id between 1 and 50),
  theme_id            smallint not null references themes(id) on delete restrict,
  ordinal             smallint not null check (ordinal between 1 and 5),
  body_md             text not null,                            -- Markdown + KaTeX (decision DEC-15)
  difficulty          difficulty not null,
  reward_coins        int not null check (reward_coins >= 0),   -- fixed per question; an admin never chooses it
  time_limit_seconds  int not null check (time_limit_seconds > 0),   -- the per-question timer (4:00 in the seed)
  buy_time_seconds    int not null check (buy_time_seconds > 0),
  buy_time_cost       int not null check (buy_time_cost >= 0),
  max_time_purchases  int check (max_time_purchases is null or max_time_purchases >= 0),   -- null = unlimited
  unique (theme_id, ordinal),
  unique (id, theme_id),                                         -- lets progress tables prove question ↔ theme agreement
  constraint questions_id_matches_position check (id = (theme_id - 1) * 5 + ordinal)
);

-- reviewer-only material, kept in a separate table so it can never ride along in a participant query
create table question_keys (
  question_id       smallint primary key references questions(id) on delete restrict,
  reference_answer  text not null,
  solution_notes    text
);

create table hints (
  id           smallint primary key check (id between 1 and 100),
  question_id  smallint not null references questions(id) on delete restrict,
  tier         smallint not null check (tier in (1, 2)),
  body_md      text not null,
  cost         int not null check (cost >= 0),                  -- configurable content data
  unique (question_id, tier),
  unique (id, question_id)
);

-- ===== 20261006000005_team_progress.sql =====
-- Patch B / migration 5 of 9 — per-team progress: unlocked themes, question states and timers, drafts, hints.

create table team_themes (               -- a row exists iff the theme is unlocked
  team_id      uuid not null references teams(id) on delete restrict,
  theme_id     smallint not null references themes(id) on delete restrict,
  unlocked_by  uuid not null,
  unlocked_at  timestamptz not null,
  cost_paid    int not null check (cost_paid >= 0),
  primary key (team_id, theme_id),
  constraint team_themes_member_in_team foreign key (unlocked_by, team_id) references team_members(id, team_id) on delete restrict
);

-- 5 rows are created when a theme is unlocked: Q1 AVAILABLE (no timer until a participant enters it → start_question),
-- Q2..Q5 LOCKED. A question timer starts when the question becomes ACTIVE — never at theme unlock.
create table team_questions (
  team_id                 uuid not null references teams(id) on delete restrict,
  question_id             smallint not null,
  theme_id                smallint not null,                    -- denormalised for indexes; kept consistent by the FK below
  ordinal                 smallint not null check (ordinal between 1 and 5),
  state                   question_state not null default 'LOCKED',
  timer_deadline          timestamptz,            -- set iff ACTIVE (authoritative, shared by all members)
  timer_remaining_seconds int,                    -- set iff PENDING_APPROVAL (timer frozen while approval is pending)
  extra_seconds           int not null default 0 check (extra_seconds >= 0),   -- total purchased, informational
  time_purchase_count     int not null default 0 check (time_purchase_count >= 0),
  activated_at            timestamptz,            -- set when the question becomes ACTIVE (the timer start)
  approved_at             timestamptz,
  timed_out_at            timestamptz,
  primary key (team_id, question_id),
  constraint team_questions_question_fk foreign key (question_id, theme_id) references questions(id, theme_id) on delete restrict,
  constraint team_questions_theme_unlocked_fk foreign key (team_id, theme_id) references team_themes(team_id, theme_id) on delete restrict,
  constraint team_questions_active_has_deadline   check ((state = 'ACTIVE') = (timer_deadline is not null)),
  constraint team_questions_pending_has_remaining check ((state = 'PENDING_APPROVAL') = (timer_remaining_seconds is not null)),
  constraint team_questions_remaining_nonneg      check (timer_remaining_seconds is null or timer_remaining_seconds >= 0),
  -- LOCKED and AVAILABLE questions have never been started: no timer start is recorded
  constraint team_questions_unstarted_no_activation check ((state in ('LOCKED', 'AVAILABLE')) = (activated_at is null)),
  -- INV-04: only Q1 is ever AVAILABLE (Q2..Q5 go LOCKED -> ACTIVE when the previous question is approved)
  constraint team_questions_available_only_q1 check (state <> 'AVAILABLE' or ordinal = 1),
  constraint team_questions_approved_at  check ((state = 'APPROVED')  = (approved_at is not null)),
  constraint team_questions_timed_out_at check ((state = 'TIMED_OUT') = (timed_out_at is not null))
);
create index tq_team_state_idx on team_questions (team_id, state);
create index tq_due_idx        on team_questions (timer_deadline) where state = 'ACTIVE';   -- timeout sweeper

-- QN+1 cannot become ACTIVE / PENDING_APPROVAL / APPROVED / TIMED_OUT until QN is APPROVED (database-level guard).
create function app.question_order_guard() returns trigger language plpgsql as $$
begin
  if new.ordinal > 1
     and new.state in ('ACTIVE', 'PENDING_APPROVAL', 'APPROVED', 'TIMED_OUT')
     and not exists (select 1 from team_questions p
                      where p.team_id = new.team_id and p.theme_id = new.theme_id
                        and p.ordinal = new.ordinal - 1 and p.state = 'APPROVED') then
    raise exception 'QUESTION_PREVIOUS_NOT_APPROVED' using errcode = 'P0001';
  end if;
  return new;
end $$;
create trigger team_questions_order before insert or update of state on team_questions
  for each row execute function app.question_order_guard();

create table answer_drafts (             -- one shared draft per team+question; KEPT after a rejection (locked UI-2.1 rule)
  team_id      uuid not null references teams(id) on delete restrict,
  question_id  smallint not null references questions(id) on delete restrict,
  answer       text not null default '',
  explanation  text not null default '',
  version      int  not null default 0,  -- optimistic concurrency (see API_SPEC saveDraft)
  updated_by   uuid,
  updated_at   timestamptz not null default now(),
  primary key (team_id, question_id),
  constraint answer_drafts_length check (length(answer) <= 10000 and length(explanation) <= 10000),
  constraint answer_drafts_member_in_team foreign key (updated_by, team_id) references team_members(id, team_id) on delete restrict
);

create table hint_purchases (
  team_id       uuid not null references teams(id) on delete restrict,
  hint_id       smallint not null references hints(id) on delete restrict,
  purchased_by  uuid not null,
  cost_paid     int not null check (cost_paid >= 0),
  purchased_at  timestamptz not null,
  primary key (team_id, hint_id),        -- a team can never pay twice for the same hint
  constraint hint_purchases_member_in_team foreign key (purchased_by, team_id) references team_members(id, team_id) on delete restrict
);

-- Tier 2 requires Tier 1 of the same question (second guard; buy_hint will check first, under the team lock)
create function app.hint_tier_order() returns trigger language plpgsql as $$
begin
  if (select tier from hints where id = new.hint_id) = 2
     and not exists (select 1
                       from hint_purchases p
                       join hints h1 on h1.id = p.hint_id and h1.tier = 1
                      where p.team_id = new.team_id
                        and h1.question_id = (select question_id from hints where id = new.hint_id)) then
    raise exception 'HINT_TIER1_REQUIRED' using errcode = 'P0001';
  end if;
  return new;
end $$;
create trigger hint_purchases_tier_order before insert on hint_purchases
  for each row execute function app.hint_tier_order();

-- ===== 20261006000006_submissions_and_coins.sql =====
-- Patch B / migration 6 of 9 — submissions (full history) and the immutable coin ledger.

create table submissions (
  id            uuid primary key default gen_random_uuid(),
  team_id       uuid not null references teams(id) on delete restrict,
  question_id   smallint not null references questions(id) on delete restrict,
  member_id     uuid not null,                         -- the member (M1–M4) who pressed Submit
  answer        text not null check (length(answer) between 1 and 10000),
  explanation   text not null check (length(explanation) <= 10000),
  status        submission_status not null default 'PENDING',
  submitted_at  timestamptz not null,
  reviewed_by   uuid references staff_users(id) on delete restrict,
  reviewed_at   timestamptz,
  review_note   text,                    -- optional reviewer note shown to the team
  reward_awarded int check (reward_awarded is null or reward_awarded >= 0),
  created_at    timestamptz not null default now(),
  constraint submissions_member_in_team foreign key (member_id, team_id) references team_members(id, team_id) on delete restrict,
  constraint submissions_reviewed_iff_decided check ((status = 'PENDING') = (reviewed_at is null)),
  constraint submissions_decided_has_reviewer check (status = 'PENDING' or reviewed_by is not null),
  constraint submissions_reward_only_if_approved check (reward_awarded is null or status = 'APPROVED')
);
-- only ONE pending submission per team+question, enforced by the database; REJECTED rows stay forever (auditable)
create unique index submissions_one_pending on submissions (team_id, question_id) where status = 'PENDING';
create index submissions_queue_idx on submissions (submitted_at) where status = 'PENDING';
create index submissions_team_idx  on submissions (team_id, question_id, submitted_at);
create index submissions_member_idx on submissions (member_id);

-- Immutable ledger. teams.coins is the authoritative balance; the ledger explains every change to it.
create table coin_transactions (
  id              bigserial primary key,
  team_id         uuid not null references teams(id) on delete restrict,
  type            coin_tx_type not null,
  amount          int  not null check (amount <> 0),               -- signed: spends negative, rewards positive
  balance_after   int  not null check (balance_after >= 0),
  theme_id        smallint references themes(id) on delete restrict,
  hint_id         smallint references hints(id) on delete restrict,
  question_id     smallint references questions(id) on delete restrict,
  submission_id   uuid     references submissions(id) on delete restrict,
  purchase_seq    int,                           -- TIME_PURCHASE: team_questions.time_purchase_count after the buy
  member_id       uuid,
  staff_id        uuid references staff_users(id) on delete restrict,
  created_at      timestamptz not null,
  constraint coin_tx_member_in_team foreign key (member_id, team_id) references team_members(id, team_id) on delete restrict,
  constraint coin_tx_sign check (
        (type in ('THEME_UNLOCK', 'HINT_PURCHASE', 'TIME_PURCHASE') and amount < 0)
     or (type in ('INITIAL_GRANT', 'QUESTION_REWARD') and amount > 0)
     or type = 'ADMIN_ADJUSTMENT'),
  -- each spend/reward names the thing it is for, so it can be made idempotent below
  constraint coin_tx_subject check (
        (type = 'THEME_UNLOCK'    and theme_id is not null)
     or (type = 'HINT_PURCHASE'   and hint_id is not null)
     or (type = 'TIME_PURCHASE'   and question_id is not null and purchase_seq is not null)
     or (type = 'QUESTION_REWARD' and question_id is not null)
     or (type = 'ADMIN_ADJUSTMENT' and staff_id is not null)
     or (type = 'INITIAL_GRANT')),
  constraint coin_tx_purchase_seq_positive check (purchase_seq is null or purchase_seq >= 1)
);
-- "cannot happen twice" guarantees, enforced at the ledger level (no duplicate grant, deduction or reward)
create unique index ctx_initial    on coin_transactions (team_id)                            where type = 'INITIAL_GRANT';
create unique index ctx_theme      on coin_transactions (team_id, theme_id)                  where type = 'THEME_UNLOCK';
create unique index ctx_hint       on coin_transactions (team_id, hint_id)                   where type = 'HINT_PURCHASE';
create unique index ctx_reward     on coin_transactions (team_id, question_id)               where type = 'QUESTION_REWARD';
create unique index ctx_time       on coin_transactions (team_id, question_id, purchase_seq) where type = 'TIME_PURCHASE';
create index ctx_team_idx          on coin_transactions (team_id, id);

-- Append-only: ledger rows are never updated, deleted or truncated (corrections are new ADMIN_ADJUSTMENT rows).
create function app.ledger_immutable() returns trigger language plpgsql as $$
begin raise exception 'coin_transactions is append-only'; end $$;
create trigger coin_tx_no_update before update or delete on coin_transactions
  for each row execute function app.ledger_immutable();
create trigger coin_tx_no_truncate before truncate on coin_transactions
  for each statement execute function app.ledger_immutable();

-- Running-balance chain: balance_after must equal the previous balance + amount (0 before the first row), and the
-- INITIAL_GRANT must equal competition.initial_coins. Concurrent inserts for one team serialise on the team row lock.
create function app.ledger_balance_chain() returns trigger language plpgsql as $$
declare prev int;
begin
  perform 1 from teams where id = new.team_id for update;
  select balance_after into prev from coin_transactions where team_id = new.team_id order by id desc limit 1;
  prev := coalesce(prev, 0);
  if new.balance_after <> prev + new.amount then
    raise exception 'LEDGER_BALANCE_MISMATCH: balance_after % <> % + %', new.balance_after, prev, new.amount
      using errcode = 'P0001';
  end if;
  if new.type = 'INITIAL_GRANT' and new.amount <> (select initial_coins from competition where id = 1) then
    raise exception 'LEDGER_INITIAL_GRANT_MISMATCH' using errcode = 'P0001';
  end if;
  return new;
end $$;
create trigger coin_tx_balance_chain before insert on coin_transactions
  for each row execute function app.ledger_balance_chain();

-- ===== 20261006000007_audit_and_support.sql =====
-- Patch B / migration 7 of 9 — idempotency log, append-only audit trail and supporting tables.

create table request_log (
  team_id       uuid not null,                   -- or the staff id for staff operations
  idem_key      uuid not null,                   -- client-generated Idempotency-Key
  operation     text not null,
  response      jsonb not null,
  created_at    timestamptz not null default now(),
  primary key (team_id, idem_key)
);
create index request_log_created_idx on request_log (created_at);   -- hourly purge

-- Event types are catalogued in docs/STATE_MACHINE.md §8 (kept as text so the catalogue can grow without a migration).
create table audit_events (
  id              bigserial primary key,
  occurred_at     timestamptz not null default now(),
  actor_kind      text not null check (actor_kind in ('STAFF', 'MEMBER', 'SYSTEM')),
  staff_id        uuid,
  member_id       uuid,
  team_id         uuid,
  event_type      text not null check (event_type <> ''),
  entity_type     text,
  entity_id       text,
  payload         jsonb not null default '{}',   -- before/after values, amounts, reasons
  request_id      uuid,
  ip              inet,
  constraint audit_actor_matches_kind check (
        (actor_kind = 'STAFF'  and staff_id is not null)
     or (actor_kind = 'MEMBER' and member_id is not null)
     or (actor_kind = 'SYSTEM'))
);
create index audit_team_idx on audit_events (team_id, id);
create index audit_type_idx on audit_events (event_type, id);

create function app.audit_immutable() returns trigger language plpgsql as $$
begin raise exception 'audit_events is append-only'; end $$;
create trigger audit_no_update before update or delete on audit_events
  for each row execute function app.audit_immutable();
create trigger audit_no_truncate before truncate on audit_events
  for each statement execute function app.audit_immutable();
revoke update, delete, truncate on audit_events from public, anon, authenticated, service_role;

create table leaderboard_snapshot (      -- single row, refreshed at most every 60 s
  id           smallint primary key default 1 check (id = 1),
  computed_at  timestamptz not null,
  rows         jsonb not null              -- [{rank, team_id, team_name, score, status}]
);

create table auth_throttle (             -- login rate limiting; keyed per account, NOT per IP
  key           text primary key,        -- 'team:<login_id>' | 'staff:<username>'
  window_start  timestamptz not null,
  attempts      int not null check (attempts >= 0),
  locked_until  timestamptz
);

create table ufm_challenges (            -- server-side second step for destructive admin actions (two-step confirmation)
  id          uuid primary key default gen_random_uuid(),
  staff_id    uuid not null references staff_users(id) on delete restrict,
  team_id     uuid not null references teams(id) on delete restrict,
  action      text not null check (action in ('RESET_SCORE', 'DISQUALIFY')),
  expires_at  timestamptz not null,
  used_at     timestamptz,
  created_at  timestamptz not null default now()
);
create index ufm_challenges_team_idx on ufm_challenges (team_id);

-- ===== 20261006000008_views_and_invariants.sql =====
-- Patch B / migration 8 of 9 — derived views and read-only invariant checkers (no game logic).

-- progress per team+theme (5 = QUESTIONS_PER_THEME)
create view team_theme_progress with (security_invoker = true) as
select team_id, theme_id,
       count(*) filter (where state = 'APPROVED') as approved_count,
       coalesce(bool_or(state = 'TIMED_OUT'), false) as has_timed_out,
       count(*) filter (where state = 'APPROVED') = 5 as completed
from team_questions group by team_id, theme_id;

-- presence: OFFLINE / ONLINE (a member is ONLINE while a live session has been seen in the last 75 s)
create view member_presence with (security_invoker = true) as
select m.id as member_id, m.team_id, m.slot,
       (case when exists (select 1 from sessions s
                           where s.member_id = m.id and s.revoked_at is null
                             and s.last_seen_at > app.now() - interval '75 seconds')
             then 'ONLINE' else 'OFFLINE' end)::presence_state as presence
from team_members m;

-- Invariant checkers: each returns the offending rows and must be empty at all times.
create view app.invariant_coin_balance_mismatch as          -- INV: teams.coins = last ledger balance_after
select t.id as team_id, t.coins, coalesce(l.balance_after, 0) as ledger_balance
from teams t
left join lateral (select balance_after from coin_transactions c where c.team_id = t.id order by c.id desc limit 1) l on true
where t.coins <> coalesce(l.balance_after, 0);

create view app.invariant_team_member_count as              -- INV: 1..4 members per team once the team exists
select t.id as team_id, count(m.id) as members
from teams t left join team_members m on m.team_id = t.id
group by t.id having count(m.id) not between 1 and 4;

-- ===== 20261006000009_security_rls.sql =====
-- Patch B / migration 9 of 9 — security foundation (decision A2/A3, docs/SECURITY.md SEC-06).
--
-- Model: the browser holds no database credentials that can read or write anything. Every table has row level
-- security ENABLED and FORCED and there are NO policies for anon/authenticated, so the Supabase anon/authenticated
-- keys can see nothing. All access goes through server code using the service role (never exposed to the browser),
-- and, from Phase 5, through SECURITY DEFINER engine functions that check ownership server-side:
--   PARTICIPANT → only their own team (session.team_id), ADMIN → only teams with teams.admin_id = their id,
--   SUPER_ADMIN → everything. Ownership is therefore enforced by the server, never by the client.

do $$
declare t record;
begin
  for t in select c.relname from pg_class c join pg_namespace n on n.oid = c.relnamespace
            where n.nspname = 'public' and c.relkind = 'r' loop
    execute format('alter table public.%I enable row level security', t.relname);
    execute format('alter table public.%I force row level security', t.relname);
  end loop;
end $$;

-- No default exposure through the Supabase Data API: remove every grant from the browser-facing roles.
revoke all on all tables    in schema public from public, anon, authenticated;
revoke all on all sequences in schema public from public, anon, authenticated;
revoke all on all functions in schema public from public, anon, authenticated;
alter default privileges in schema public revoke all on tables    from anon, authenticated;
alter default privileges in schema public revoke all on sequences from anon, authenticated;
alter default privileges in schema public revoke all on functions from anon, authenticated;

revoke all on schema app from public, anon, authenticated;
revoke all on all tables    in schema app from public, anon, authenticated;
revoke all on all functions in schema app from public, anon, authenticated;

-- The server (service role) works through explicit grants. The audit trail and the coin ledger stay append-only.
grant usage on schema public, app to service_role;
grant select, insert, update, delete on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;
grant select on all tables in schema app to service_role;
grant execute on all functions in schema app to service_role;
revoke update, delete, truncate on audit_events      from service_role;
revoke update, delete, truncate on coin_transactions from service_role;

-- ===== 20261006000010_buy_time_options.sql =====
-- Follow-up to Patch B / migration 10 — multiple configurable Buy Time options per question.
--
-- The participant UI offers three Buy Time options per question. The earlier single (buy_time_seconds, buy_time_cost,
-- max_time_purchases) triple on `questions` cannot represent that, so the options become a normalised table and the
-- triple is removed. Seconds, prices and caps are CONTENT DATA (seeded as placeholders), not constants in any engine code.

create table question_buy_time_options (
  id             smallint primary key check (id > 0),
  question_id    smallint not null references questions(id) on delete restrict,
  seconds        int      not null check (seconds > 0),
  cost           int      not null check (cost >= 0),
  max_purchases  int      check (max_purchases is null or max_purchases >= 0),   -- per team and question; null = unlimited
  display_order  smallint not null check (display_order > 0),
  unique (question_id, display_order),
  unique (question_id, seconds),          -- two options for the same question never add the same time
  unique (id, question_id)                -- lets purchases prove "this option belongs to this question"
);
create index qbto_question_idx on question_buy_time_options (question_id, display_order);

alter table questions
  drop column buy_time_seconds,
  drop column buy_time_cost,
  drop column max_time_purchases;

-- One row per Buy Time purchase: a snapshot of what was bought and paid, so later content edits never rewrite history.
-- (team_id, question_id, seq) mirrors coin_transactions.purchase_seq and team_questions.time_purchase_count, which makes
-- the future atomic `buy_time` operation idempotent (a retried or replayed purchase is rejected) and detects double clicks.
create table team_time_purchases (
  team_id       uuid     not null references teams(id) on delete restrict,
  question_id   smallint not null,
  seq           int      not null check (seq >= 1),
  option_id     smallint not null,
  seconds_added int      not null check (seconds_added > 0),
  cost_paid     int      not null check (cost_paid >= 0),
  purchased_by  uuid     not null,
  purchased_at  timestamptz not null,
  primary key (team_id, question_id, seq),
  constraint ttp_team_question_fk foreign key (team_id, question_id) references team_questions(team_id, question_id) on delete restrict,
  constraint ttp_option_fk        foreign key (option_id, question_id) references question_buy_time_options(id, question_id) on delete restrict,
  constraint ttp_member_in_team   foreign key (purchased_by, team_id) references team_members(id, team_id) on delete restrict
);
create index ttp_option_idx on team_time_purchases (team_id, question_id, option_id);

-- Database-level guards for the future buy_time operation (the operation itself is Phase 5):
--   * only while the question is ACTIVE, * seq is the next number (no gaps, no replays),
--   * the recorded seconds/cost equal the option's configuration, * the option's per-team cap is not exceeded.
create function app.time_purchase_guard() returns trigger language plpgsql as $$
declare o question_buy_time_options; used int;
begin
  if (select state from team_questions where team_id = new.team_id and question_id = new.question_id) is distinct from 'ACTIVE' then
    raise exception 'BUY_TIME_NOT_ACTIVE' using errcode = 'P0001';
  end if;
  if new.seq <> (select count(*) from team_time_purchases where team_id = new.team_id and question_id = new.question_id) + 1 then
    raise exception 'TIME_PURCHASE_SEQ_MISMATCH' using errcode = 'P0001';
  end if;
  select * into o from question_buy_time_options where id = new.option_id and question_id = new.question_id;
  if found then
    if new.seconds_added <> o.seconds or new.cost_paid <> o.cost then
      raise exception 'BUY_TIME_OPTION_MISMATCH' using errcode = 'P0001';
    end if;
    select count(*) into used from team_time_purchases
     where team_id = new.team_id and question_id = new.question_id and option_id = new.option_id;
    if o.max_purchases is not null and used >= o.max_purchases then
      raise exception 'TIME_PURCHASE_LIMIT' using errcode = 'P0001';
    end if;
  end if;   -- an unknown option is rejected by ttp_option_fk
  return new;
end $$;
create trigger team_time_purchases_guard before insert on team_time_purchases
  for each row execute function app.time_purchase_guard();

-- Same security posture as every other table (see migration 9): RLS enabled and forced, no client policies.
alter table question_buy_time_options enable row level security;
alter table question_buy_time_options force  row level security;
alter table team_time_purchases       enable row level security;
alter table team_time_purchases       force  row level security;
revoke all on question_buy_time_options, team_time_purchases from public, anon, authenticated;
grant select, insert, update, delete on question_buy_time_options, team_time_purchases to service_role;
revoke update, delete on team_time_purchases from service_role;   -- purchase history is append-only

-- ===== 20261006000011_auth_functions.sql =====
-- Patch B9 / migration 11 — authentication + session functions (docs/SECURITY.md §3, docs/API_SPEC.md §3).
--
-- What this adds: password hashing helpers, per-account login throttling, participant and staff login, session
-- resolution and logout, and the one-time Super Admin provisioning function. It adds NO game rule, timer, coin,
-- realtime or team/admin management function, and it never starts a team's timer.
--
-- Hashing (docs/SECURITY.md SEC-02 permits "argon2id (or bcrypt cost >= 12)"): bcrypt, cost 12, through pgcrypto, so
-- the credential check, the throttle, the session row and the audit row are one atomic database call. bcrypt only
-- reads the first 72 bytes of a password, so longer passwords are refused when hashing and never match when verifying.
--
-- Privileges: every function below is created, then EXECUTE is revoked from PUBLIC (and anon/authenticated) and granted
-- to service_role only. Nothing relies on PostgreSQL's default function privileges (PUBLIC may execute by default).
-- The callable functions are SECURITY DEFINER with a pinned search_path.
--
-- Failure results are RETURNED as {"ok": false, "code": ...}, never raised, so the throttle counter and the audit row
-- written for a failed attempt are committed rather than rolled back with an exception.

-- ---------------------------------------------------------------------------------------------------------------
-- Password helpers
-- ---------------------------------------------------------------------------------------------------------------

-- A valid bcrypt hash of a throw-away value. Verifying against it when an account does not exist keeps the response
-- time of "unknown account" and "wrong password" alike (no user-enumeration timing signal).
create function app.auth_dummy_hash() returns text language sql immutable as
$$ select '$2a$12$u2KmYDrytDphw1TLDqmqXulLVLqrbmv3/JEfvyopauzarb6O4nlly'::text $$;

create function app.hash_password(p_password text) returns text
language plpgsql
set search_path = pg_catalog, public, extensions, pg_temp
as $$
begin
  if p_password is null or p_password = '' then
    raise exception 'password must not be empty' using errcode = '22023';
  end if;
  if octet_length(p_password) > 72 then
    raise exception 'password is longer than 72 bytes (bcrypt limit)' using errcode = '22023';
  end if;
  return crypt(p_password, gen_salt('bf', 12));
end $$;

-- True only for a well-formed bcrypt hash that matches. Always performs one bcrypt comparison (against the dummy
-- hash when `p_hash` is null or malformed) so the cost does not depend on whether the account exists.
create function app.verify_password(p_password text, p_hash text) returns boolean
language plpgsql
set search_path = pg_catalog, public, extensions, pg_temp
as $$
declare
  v_real boolean := p_hash is not null and p_hash ~ '^\$2[abxy]\$[0-9]{2}\$[./A-Za-z0-9]{53}$';
  v_hash text := case when v_real then p_hash else app.auth_dummy_hash() end;
  v_match boolean := crypt(coalesce(p_password, ''), v_hash) = v_hash;
begin
  return v_real and v_match and octet_length(coalesce(p_password, '')) <= 72;
end $$;

-- ---------------------------------------------------------------------------------------------------------------
-- Throttling (docs/API_SPEC.md §8): 8 failures per account per 10 minutes, then an exponential delay
-- (30 s, 60 s, 120 s, 240 s, capped at 300 s). Keyed per account ('team:<login_id>' / 'staff:<username>'), never by IP.
-- ---------------------------------------------------------------------------------------------------------------

-- Seconds the account must still wait (0 = the attempt may proceed).
create function app.auth_throttle_retry_after(p_key text) returns int
language sql stable
set search_path = pg_catalog, public, pg_temp
as $$
  select coalesce((select greatest(0, ceil(extract(epoch from (t.locked_until - app.now()))))::int
                     from auth_throttle t where t.key = p_key), 0)
$$;

-- Records one failed attempt; returns the lock length in seconds applied by this failure (0 = none yet).
create function app.auth_throttle_fail(p_key text) returns int
language plpgsql
set search_path = pg_catalog, public, pg_temp
as $$
declare
  v_now timestamptz := app.now();
  v_attempts int;
  v_delay int := 0;
begin
  insert into auth_throttle as t (key, window_start, attempts)
  values (p_key, v_now, 1)
  on conflict (key) do update
    set window_start = case when t.window_start < v_now - interval '10 minutes' then v_now else t.window_start end,
        attempts     = case when t.window_start < v_now - interval '10 minutes' then 1 else t.attempts + 1 end
  returning attempts into v_attempts;

  if v_attempts >= 8 then
    v_delay := least(300, 30 * (2 ^ least(v_attempts - 8, 10))::int);
    update auth_throttle set locked_until = v_now + make_interval(secs => v_delay) where key = p_key;
  end if;
  return v_delay;
end $$;

-- A successful login clears the account's counter and any lock.
create function app.auth_throttle_clear(p_key text) returns void
language sql
set search_path = pg_catalog, public, pg_temp
as $$ delete from auth_throttle where key = p_key $$;

-- ---------------------------------------------------------------------------------------------------------------
-- participant_login: team login ID + team password + member admission number
-- Same generic result for an unknown team, a wrong password, an unknown admission number and an admission number that
-- belongs to another team. Does NOT start the team timer. Permitted only while the competition is RUNNING or PAUSED.
-- ---------------------------------------------------------------------------------------------------------------
create function public.participant_login(
  p_login_id     text,
  p_password     text,
  p_admission_no text,
  p_token_hash   bytea,
  p_ip           inet default null,
  p_user_agent   text default null
) returns jsonb
language plpgsql security definer
set search_path = pg_catalog, public, extensions, app, pg_temp
as $$
declare
  v_now      timestamptz := app.now();
  v_login    text := btrim(coalesce(p_login_id, ''));
  v_key      text := 'team:' || lower(btrim(coalesce(p_login_id, '')));
  v_retry    int;
  v_team     teams%rowtype;
  v_member   team_members%rowtype;
  v_pw_ok    boolean;
  v_reason   text;
  v_status   competition_status;
  v_session  uuid;
  v_expires  timestamptz;
  v_replaced int;
begin
  if p_token_hash is null or octet_length(p_token_hash) <> 32 then
    raise exception 'participant_login: token hash must be exactly 32 bytes' using errcode = '22023';
  end if;

  v_retry := app.auth_throttle_retry_after(v_key);
  if v_retry > 0 then
    return jsonb_build_object('ok', false, 'code', 'RATE_LIMITED', 'retry_after_seconds', v_retry);
  end if;

  select * into v_team from teams where login_id = v_login::citext;
  v_pw_ok := app.verify_password(p_password, v_team.password_hash);   -- always one bcrypt comparison
  if v_team.id is not null then
    select * into v_member from team_members
     where team_id = v_team.id and admission_no = upper(btrim(coalesce(p_admission_no, '')));
  end if;

  if v_team.id is null or not v_pw_ok or v_member.id is null then
    v_reason := case when v_team.id is null then 'UNKNOWN_TEAM'
                     when not v_pw_ok then 'BAD_PASSWORD' else 'BAD_ADMISSION_NO' end;
    perform app.auth_throttle_fail(v_key);
    insert into audit_events (occurred_at, actor_kind, team_id, event_type, entity_type, payload, ip)
    values (v_now, 'SYSTEM', v_team.id, 'LOGIN_FAILED', 'TEAM_LOGIN',
            jsonb_build_object('subject', 'MEMBER', 'account_key', left(v_key, 80), 'reason', v_reason,
                               'user_agent', left(p_user_agent, 256)), p_ip);
    return jsonb_build_object('ok', false, 'code', 'INVALID_CREDENTIALS');
  end if;

  select status into v_status from competition where id = 1;
  if v_status is null or v_status not in ('RUNNING', 'PAUSED') then
    perform app.auth_throttle_clear(v_key);   -- the credentials were right; only the competition is not open
    insert into audit_events (occurred_at, actor_kind, member_id, team_id, event_type, entity_type, payload, ip)
    values (v_now, 'MEMBER', v_member.id, v_team.id, 'LOGIN_FAILED', 'TEAM_LOGIN',
            jsonb_build_object('subject', 'MEMBER', 'account_key', left(v_key, 80), 'reason', 'COMPETITION_NOT_OPEN',
                               'competition_status', v_status, 'user_agent', left(p_user_agent, 256)), p_ip);
    return jsonb_build_object('ok', false, 'code', 'COMPETITION_NOT_RUNNING', 'competition_status', v_status);
  end if;

  -- serialise concurrent logins of the same member, then supersede the previous live session (one live session per member)
  perform 1 from team_members where id = v_member.id for update;
  update sessions
     set revoked_at = v_now,
         revoke_reason = case when expires_at > v_now then 'SUPERSEDED' else 'EXPIRED' end
   where member_id = v_member.id and revoked_at is null;
  get diagnostics v_replaced = row_count;

  v_expires := v_now + interval '12 hours';
  insert into sessions (token_hash, kind, team_id, member_id, created_at, last_seen_at, expires_at, ip, user_agent)
  values (p_token_hash, 'MEMBER', v_team.id, v_member.id, v_now, v_now, v_expires, p_ip, left(p_user_agent, 256))
  returning id into v_session;

  perform app.auth_throttle_clear(v_key);
  insert into audit_events (occurred_at, actor_kind, member_id, team_id, event_type, entity_type, entity_id, payload, ip)
  values (v_now, 'MEMBER', v_member.id, v_team.id, 'MEMBER_LOGIN', 'SESSION', v_session::text,
          jsonb_build_object('superseded_sessions', v_replaced, 'user_agent', left(p_user_agent, 256)), p_ip);

  return jsonb_build_object(
    'ok', true, 'role', 'PARTICIPANT',
    'session', jsonb_build_object('id', v_session, 'expires_at', v_expires),
    'member',  jsonb_build_object('id', v_member.id, 'slot', v_member.slot),
    'team',    jsonb_build_object('id', v_team.id, 'code', v_team.team_code, 'name', v_team.name,
                                  'status', v_team.status::text));
end $$;

-- ---------------------------------------------------------------------------------------------------------------
-- staff_login: username + password for ADMIN and SUPER_ADMIN. Inactive accounts are rejected with the same generic
-- result as a wrong password. Staff sessions are not unique per account (the schema only constrains members).
-- ---------------------------------------------------------------------------------------------------------------
create function public.staff_login(
  p_username   text,
  p_password   text,
  p_token_hash bytea,
  p_ip         inet default null,
  p_user_agent text default null
) returns jsonb
language plpgsql security definer
set search_path = pg_catalog, public, extensions, app, pg_temp
as $$
declare
  v_now     timestamptz := app.now();
  v_name    text := btrim(coalesce(p_username, ''));
  v_key     text := 'staff:' || lower(btrim(coalesce(p_username, '')));
  v_retry   int;
  v_staff   staff_users%rowtype;
  v_pw_ok   boolean;
  v_reason  text;
  v_session uuid;
  v_expires timestamptz;
begin
  if p_token_hash is null or octet_length(p_token_hash) <> 32 then
    raise exception 'staff_login: token hash must be exactly 32 bytes' using errcode = '22023';
  end if;

  v_retry := app.auth_throttle_retry_after(v_key);
  if v_retry > 0 then
    return jsonb_build_object('ok', false, 'code', 'RATE_LIMITED', 'retry_after_seconds', v_retry);
  end if;

  select * into v_staff from staff_users where username = v_name::citext;
  v_pw_ok := app.verify_password(p_password, v_staff.password_hash);

  if v_staff.id is null or not v_pw_ok or not v_staff.is_active then
    v_reason := case when v_staff.id is null then 'UNKNOWN_ACCOUNT'
                     when not v_pw_ok then 'BAD_PASSWORD' else 'ACCOUNT_INACTIVE' end;
    perform app.auth_throttle_fail(v_key);
    insert into audit_events (occurred_at, actor_kind, event_type, entity_type, payload, ip)
    values (v_now, 'SYSTEM', 'LOGIN_FAILED', 'STAFF_LOGIN',
            jsonb_build_object('subject', 'STAFF', 'account_key', left(v_key, 80), 'reason', v_reason,
                               'user_agent', left(p_user_agent, 256)), p_ip);
    return jsonb_build_object('ok', false, 'code', 'INVALID_CREDENTIALS');
  end if;

  v_expires := v_now + interval '12 hours';
  insert into sessions (token_hash, kind, staff_id, created_at, last_seen_at, expires_at, ip, user_agent)
  values (p_token_hash, 'STAFF', v_staff.id, v_now, v_now, v_expires, p_ip, left(p_user_agent, 256))
  returning id into v_session;
  update staff_users set last_login_at = v_now where id = v_staff.id;

  perform app.auth_throttle_clear(v_key);
  insert into audit_events (occurred_at, actor_kind, staff_id, event_type, entity_type, entity_id, payload, ip)
  values (v_now, 'STAFF', v_staff.id, 'STAFF_LOGIN', 'SESSION', v_session::text,
          jsonb_build_object('role', v_staff.role::text, 'user_agent', left(p_user_agent, 256)), p_ip);

  return jsonb_build_object(
    'ok', true, 'role', v_staff.role::text,
    'session', jsonb_build_object('id', v_session, 'expires_at', v_expires),
    'staff',   jsonb_build_object('id', v_staff.id, 'username', v_staff.username::text,
                                  'display_name', v_staff.display_name));
end $$;

-- ---------------------------------------------------------------------------------------------------------------
-- resolve_session: token hash -> principal. Rejects unknown, revoked and expired sessions (an expired one is revoked
-- as EXPIRED) and sessions of disabled staff (revoked as ADMIN_DISABLED). A live session gets last_seen_at = now.
-- ---------------------------------------------------------------------------------------------------------------
create function public.resolve_session(p_token_hash bytea) returns jsonb
language plpgsql security definer
set search_path = pg_catalog, public, extensions, app, pg_temp
as $$
declare
  v_now     timestamptz := app.now();
  v_s       sessions%rowtype;
  v_staff   staff_users%rowtype;
  v_member  team_members%rowtype;
  v_team    teams%rowtype;
  v_session jsonb;
begin
  if p_token_hash is null or octet_length(p_token_hash) <> 32 then
    return jsonb_build_object('ok', false, 'code', 'UNAUTHENTICATED');
  end if;

  select * into v_s from sessions where token_hash = p_token_hash for update;
  if v_s.id is null or v_s.revoked_at is not null then
    return jsonb_build_object('ok', false, 'code', 'UNAUTHENTICATED');
  end if;
  if v_s.expires_at <= v_now then
    update sessions set revoked_at = v_now, revoke_reason = 'EXPIRED' where id = v_s.id;
    return jsonb_build_object('ok', false, 'code', 'UNAUTHENTICATED');
  end if;

  if v_s.kind = 'STAFF' then
    select * into v_staff from staff_users where id = v_s.staff_id;
    if not v_staff.is_active then
      update sessions set revoked_at = v_now, revoke_reason = 'ADMIN_DISABLED' where id = v_s.id;
      return jsonb_build_object('ok', false, 'code', 'UNAUTHENTICATED');
    end if;
  end if;

  update sessions set last_seen_at = v_now where id = v_s.id;
  v_session := jsonb_build_object('id', v_s.id, 'expires_at', v_s.expires_at);

  if v_s.kind = 'STAFF' then
    return jsonb_build_object('ok', true, 'role', v_staff.role::text, 'session', v_session,
      'staff', jsonb_build_object('id', v_staff.id, 'username', v_staff.username::text,
                                  'display_name', v_staff.display_name));
  end if;

  select * into v_member from team_members where id = v_s.member_id;
  select * into v_team from teams where id = v_s.team_id;
  return jsonb_build_object('ok', true, 'role', 'PARTICIPANT', 'session', v_session,
    'member', jsonb_build_object('id', v_member.id, 'slot', v_member.slot),
    'team',   jsonb_build_object('id', v_team.id, 'code', v_team.team_code, 'name', v_team.name,
                                 'status', v_team.status::text));
end $$;

-- ---------------------------------------------------------------------------------------------------------------
-- revoke_session: logout. Idempotent: an unknown, already revoked or expired token is not an error and reveals nothing.
-- ---------------------------------------------------------------------------------------------------------------
create function public.revoke_session(p_token_hash bytea) returns jsonb
language plpgsql security definer
set search_path = pg_catalog, public, extensions, app, pg_temp
as $$
declare
  v_now timestamptz := app.now();
  v_s   sessions%rowtype;
begin
  if p_token_hash is null or octet_length(p_token_hash) <> 32 then
    return jsonb_build_object('ok', true, 'revoked', false);
  end if;

  select * into v_s from sessions where token_hash = p_token_hash for update;
  if v_s.id is null or v_s.revoked_at is not null then
    return jsonb_build_object('ok', true, 'revoked', false);
  end if;
  if v_s.expires_at <= v_now then
    update sessions set revoked_at = v_now, revoke_reason = 'EXPIRED' where id = v_s.id;
    return jsonb_build_object('ok', true, 'revoked', false);
  end if;

  update sessions set revoked_at = v_now, revoke_reason = 'LOGOUT' where id = v_s.id;
  if v_s.kind = 'STAFF' then
    insert into audit_events (occurred_at, actor_kind, staff_id, event_type, entity_type, entity_id)
    values (v_now, 'STAFF', v_s.staff_id, 'STAFF_LOGOUT', 'SESSION', v_s.id::text);
  else
    insert into audit_events (occurred_at, actor_kind, member_id, team_id, event_type, entity_type, entity_id)
    values (v_now, 'MEMBER', v_s.member_id, v_s.team_id, 'MEMBER_LOGOUT', 'SESSION', v_s.id::text);
  end if;
  return jsonb_build_object('ok', true, 'revoked', true);
end $$;

-- ---------------------------------------------------------------------------------------------------------------
-- provision_superadmin: used only by `npm run provision:superadmin`. Hashes the password in the database, so the
-- plaintext never reaches a file or a log. Exactly one Super Admin can exist (unique index staff_one_super_admin).
-- ---------------------------------------------------------------------------------------------------------------
create function app.provision_superadmin(p_username text, p_display_name text, p_password text) returns uuid
language plpgsql security definer
set search_path = pg_catalog, public, extensions, app, pg_temp
as $$
declare
  v_id uuid;
begin
  if p_username is null or p_username !~ '^[A-Za-z0-9._-]{3,64}$' then
    raise exception 'INVALID_USERNAME' using errcode = '22023';
  end if;
  if p_display_name is null or btrim(p_display_name) = '' or length(p_display_name) > 100 then
    raise exception 'INVALID_DISPLAY_NAME' using errcode = '22023';
  end if;
  if p_password is null or length(p_password) < 10 or octet_length(p_password) > 72 then
    raise exception 'INVALID_PASSWORD' using errcode = '22023';
  end if;
  if exists (select 1 from staff_users where role = 'SUPER_ADMIN') then
    raise exception 'SUPER_ADMIN_EXISTS' using errcode = 'P0001';
  end if;

  begin
    insert into staff_users (username, display_name, password_hash, role)
    values (p_username, btrim(p_display_name), app.hash_password(p_password), 'SUPER_ADMIN')
    returning id into v_id;
  exception when unique_violation then
    raise exception 'SUPER_ADMIN_EXISTS' using errcode = 'P0001';   -- lost a race, or the username is taken
  end;

  insert into audit_events (actor_kind, event_type, entity_type, entity_id, payload)
  values ('SYSTEM', 'SUPER_ADMIN_PROVISIONED', 'STAFF', v_id::text, jsonb_build_object('username', p_username));
  return v_id;
end $$;

-- ---------------------------------------------------------------------------------------------------------------
-- Privileges. Explicit for every function above: no PUBLIC, no anon, no authenticated; service_role only.
-- ---------------------------------------------------------------------------------------------------------------
revoke all on function app.auth_dummy_hash()                                   from public, anon, authenticated;
revoke all on function app.hash_password(text)                                 from public, anon, authenticated;
revoke all on function app.verify_password(text, text)                         from public, anon, authenticated;
revoke all on function app.auth_throttle_retry_after(text)                     from public, anon, authenticated;
revoke all on function app.auth_throttle_fail(text)                            from public, anon, authenticated;
revoke all on function app.auth_throttle_clear(text)                           from public, anon, authenticated;
revoke all on function app.provision_superadmin(text, text, text)              from public, anon, authenticated;
revoke all on function public.participant_login(text, text, text, bytea, inet, text) from public, anon, authenticated;
revoke all on function public.staff_login(text, text, bytea, inet, text)       from public, anon, authenticated;
revoke all on function public.resolve_session(bytea)                           from public, anon, authenticated;
revoke all on function public.revoke_session(bytea)                            from public, anon, authenticated;

grant execute on function app.auth_dummy_hash()                                   to service_role;
grant execute on function app.hash_password(text)                                 to service_role;
grant execute on function app.verify_password(text, text)                         to service_role;
grant execute on function app.auth_throttle_retry_after(text)                     to service_role;
grant execute on function app.auth_throttle_fail(text)                            to service_role;
grant execute on function app.auth_throttle_clear(text)                           to service_role;
grant execute on function app.provision_superadmin(text, text, text)              to service_role;
grant execute on function public.participant_login(text, text, text, bytea, inet, text) to service_role;
grant execute on function public.staff_login(text, text, bytea, inet, text)       to service_role;
grant execute on function public.resolve_session(bytea)                           to service_role;
grant execute on function public.revoke_session(bytea)                            to service_role;

-- ===== 20261006000012_runtime_engine.sql =====
-- Patch B10 / migration 12 — competition runtime engine: the single team lock, request idempotency, the controlled
-- competition status operation, start_team_competition and the authoritative team snapshot.
--
-- Scope (B10 only): SETUP→RUNNING, RUNNING↔PAUSED, RUNNING/PAUSED→ENDED; team NOT_STARTED→RUNNING. No theme, question,
-- coin, submission, final-submit, UFM or realtime operation, and no scoring (`compute_team_score` does not exist yet).
--
-- Conventions (docs/STATE_MACHINE.md §1, docs/API_SPEC.md §1–2):
--   * Rejections are RAISED as `P0001` with the stable error code as the message (and optional JSON `detail`), so the
--     whole transaction rolls back. The API maps the code; no raw PostgreSQL error ever reaches a client.
--   * Every timestamp comes from app.now(); the clock is never a parameter. Times in JSON are epoch milliseconds.
--   * Principals are resolved by the server (B9 resolve_session) and passed as ids; every function re-checks them
--     (member ∈ team, staff active and SUPER_ADMIN), so authorisation is enforced twice (SECURITY.md §4).
--   * Locks are always taken in this order: competition row → teams (by id) → their children. Deadlock-free.
--   * Privileges: every function below gets an explicit REVOKE ALL … FROM PUBLIC, anon, authenticated and a
--     GRANT EXECUTE … TO service_role. Nothing relies on PostgreSQL's default function privileges.

-- ---------------------------------------------------------------------------------------------------------------
-- request_log: one row per (scope, key). `team_id` holds the team id for participant operations and the staff id for
-- staff operations (unchanged from migration 7). The new fingerprint binds a key to one operation and one actor
-- (and its parameters), so reusing a key for something else is an error instead of a silent replay.
-- ---------------------------------------------------------------------------------------------------------------
alter table request_log add column request_fingerprint text not null default '';

-- ---------------------------------------------------------------------------------------------------------------
-- Small helpers
-- ---------------------------------------------------------------------------------------------------------------
create function app.fail(p_code text, p_details jsonb default null) returns void
language plpgsql
as $$
begin
  if p_details is null then
    raise exception '%', p_code using errcode = 'P0001';
  else
    raise exception '%', p_code using errcode = 'P0001', detail = p_details::text;
  end if;
end $$;

create function app.epoch_ms(p_ts timestamptz) returns bigint
language sql immutable strict
as $$ select floor(extract(epoch from p_ts) * 1000)::bigint $$;

-- Staff authority for competition-level operations: an active SUPER_ADMIN (STATE_MACHINE §2: "Super Admin only").
create function app.require_super_admin(p_staff_id uuid) returns void
language plpgsql stable
set search_path = pg_catalog, public, app, pg_temp
as $$
begin
  if p_staff_id is null
     or not exists (select 1 from staff_users where id = p_staff_id and role = 'SUPER_ADMIN' and is_active) then
    perform app.fail('FORBIDDEN');
  end if;
end $$;

-- ---------------------------------------------------------------------------------------------------------------
-- app.lock_team — the ONE locking primitive for every future operation that touches a team.
--   1. competition row FOR SHARE: while an operation runs, the competition status cannot change under it (a start can
--      never slip through a concurrent pause), yet any number of participants proceed in parallel.
--   2. team row FOR UPDATE: all writers of one team are serialised.
-- Competition → team is the global lock order; set_competition_status takes competition FOR UPDATE and then the teams in
-- id order, so no cycle is possible. Raises NOT_FOUND for an unknown team. Callers read competition.status afterwards:
-- the share lock guarantees that the value they read stays valid until commit.
-- ---------------------------------------------------------------------------------------------------------------
create function app.lock_team(p_team_id uuid) returns teams
language plpgsql
set search_path = pg_catalog, public, app, pg_temp
as $$
declare
  v_team teams%rowtype;
begin
  perform 1 from competition where id = 1 for share;
  select * into v_team from teams where id = p_team_id for update;
  if not found then
    perform app.fail('NOT_FOUND');
  end if;
  return v_team;
end $$;

-- ---------------------------------------------------------------------------------------------------------------
-- Idempotency (STATE_MACHINE §1.1 step 1). Callers invoke these while holding the lock that serialises the scope
-- (the team lock, or the competition lock for staff operations), so two requests with one key cannot interleave.
--   idem_lookup: NULL if the key is new; the stored response if it was seen; IDEMPOTENCY_KEY_REUSED if the key was used
--   for another operation, actor or parameter. A missing key is VALIDATION_FAILED.
--   Only successes are stored: a rejected request rolled back and may be retried with the same key.
-- ---------------------------------------------------------------------------------------------------------------
create function app.idem_lookup(p_scope uuid, p_key uuid, p_operation text, p_fingerprint text) returns jsonb
language plpgsql stable
set search_path = pg_catalog, public, app, pg_temp
as $$
declare
  r request_log%rowtype;
begin
  if p_key is null then
    perform app.fail('VALIDATION_FAILED', jsonb_build_object('fields', jsonb_build_array('idempotencyKey')));
  end if;
  select * into r from request_log where team_id = p_scope and idem_key = p_key;
  if not found then
    return null;
  end if;
  if r.operation <> p_operation or r.request_fingerprint <> p_fingerprint then
    perform app.fail('IDEMPOTENCY_KEY_REUSED');
  end if;
  return r.response;
end $$;

create function app.idem_store(p_scope uuid, p_key uuid, p_operation text, p_fingerprint text, p_response jsonb)
returns void
language sql
set search_path = pg_catalog, public, app, pg_temp
as $$
  insert into request_log (team_id, idem_key, operation, response, request_fingerprint, created_at)
  values (p_scope, p_key, p_operation, p_response, p_fingerprint, app.now())
$$;

-- ---------------------------------------------------------------------------------------------------------------
-- The authoritative snapshot. Used by get_team_state AND returned by start_team_competition, so the two can never
-- disagree. A pure read: it never changes anything, not even for an expired team (it reports remaining_seconds = 0 and
-- expired = true; the transition to ENDED belongs to competition end / the later sweeper).
--
--   ref_time          = least(app.now(), team.ended_at, competition.paused_at while PAUSED)       (STATE_MACHINE §1.3)
--   remaining_seconds = greatest(0, floor(extract(epoch from ends_at - ref_time)))
-- While the competition is RUNNING and the team is not terminal this is exactly floor(ends_at - now()). A team that has
-- not started reports the full ultimate_seconds. Nothing here is stored; nothing here is client-supplied.
--
-- Never included: password hashes, session token hashes, admission numbers, question bodies, hints or reviewer keys.
-- The shape is a strict subset of docs/API_SPEC.md §7 (no score, teammates or purchasable options yet).
-- ---------------------------------------------------------------------------------------------------------------
create function app.team_state_json(p_team_id uuid, p_member_id uuid) returns jsonb
language plpgsql stable
set search_path = pg_catalog, public, app, pg_temp
as $$
declare
  v_now   timestamptz := app.now();
  t       teams%rowtype;
  c       competition%rowtype;
  m       team_members%rowtype;
  v_ref   timestamptz;
  v_rem   int;
  v_themes jsonb;
begin
  select * into t from teams where id = p_team_id;
  select * into c from competition where id = 1;
  select * into m from team_members where id = p_member_id and team_id = p_team_id;
  if t.id is null or m.id is null or c.id is null then
    perform app.fail('NOT_FOUND');
  end if;

  v_ref := least(v_now, coalesce(t.ended_at, 'infinity'::timestamptz),
                 case when c.status = 'PAUSED' then c.paused_at end);
  v_rem := case when t.ends_at is null then c.ultimate_seconds
                else greatest(0, floor(extract(epoch from (t.ends_at - v_ref))))::int end;

  select coalesce(jsonb_agg(
           jsonb_build_object(
             'id', th.id,
             'code', th.code,
             'status', case when tt.theme_id is null then 'LOCKED'
                            when coalesce(p.has_timed_out, false) then 'FAILED'
                            when coalesce(p.completed, false) then 'COMPLETED'
                            else 'IN_PROGRESS' end,
             'questions', coalesce(qs.arr, '[]'::jsonb))
           order by th.display_order), '[]'::jsonb)
    into v_themes
    from themes th
    left join team_themes tt on tt.team_id = p_team_id and tt.theme_id = th.id
    left join team_theme_progress p on p.team_id = p_team_id and p.theme_id = th.id
    left join lateral (
      select jsonb_agg(
               jsonb_build_object('id', q.question_id, 'ordinal', q.ordinal, 'state', q.state)
               || case when q.state = 'ACTIVE' then jsonb_build_object('deadline', app.epoch_ms(q.timer_deadline))
                       else '{}'::jsonb end
               order by q.ordinal) as arr
        from team_questions q
       where q.team_id = p_team_id and q.theme_id = th.id) qs on true;

  return jsonb_build_object(
    'server_now', app.epoch_ms(v_now),
    'state_version', t.state_version,
    'competition', jsonb_build_object('status', c.status),
    'me', jsonb_build_object('member_id', m.id, 'slot', m.slot, 'team_id', t.id,
                             'team_code', t.team_code, 'team_name', t.name),
    'team', jsonb_build_object(
      'status', t.status,
      'coins', t.coins,
      'started_at', app.epoch_ms(t.started_at),
      'ends_at', app.epoch_ms(t.ends_at),
      'ended_at', app.epoch_ms(t.ended_at),
      'final_submitted_at', app.epoch_ms(t.final_submitted_at),
      'duration_seconds', c.ultimate_seconds,
      'remaining_seconds', v_rem,
      'expired', (t.status = 'RUNNING' and v_ref >= t.ends_at)),
    'themes', v_themes);
end $$;

create function app.competition_json() returns jsonb
language sql stable
set search_path = pg_catalog, public, app, pg_temp
as $$
  select jsonb_build_object('status', status, 'opened_at', app.epoch_ms(opened_at), 'paused_at', app.epoch_ms(paused_at),
                            'ended_at', app.epoch_ms(ended_at), 'state_version', state_version)
    from competition where id = 1
$$;

-- ---------------------------------------------------------------------------------------------------------------
-- app.expire_team — the minimal, idempotent RUNNING → ENDED transition (STATE_MACHINE §5.4), used only by the
-- competition operations below in B10 (the sweeper and lazy expiry arrive with the game operations).
--   * The caller holds the team lock and bumps state_version (STATE_MACHINE §1.2).
--   * ended_at = least(ends_at, p_ended_at): a team never ends later than its scheduled end.
--   * ACTIVE questions whose deadline is not after that instant become TIMED_OUT (none exist before B12).
--   * NOT done yet: caching final_* (compute_team_score does not exist). They stay NULL until the scoring patch.
-- ---------------------------------------------------------------------------------------------------------------
create function app.expire_team(p_team_id uuid, p_reason text, p_ended_at timestamptz, p_staff_id uuid default null)
returns void
language plpgsql
set search_path = pg_catalog, public, app, pg_temp
as $$
declare
  t     teams%rowtype;
  v_end timestamptz;
begin
  select * into t from teams where id = p_team_id;
  if not found or t.status <> 'RUNNING' then
    return;
  end if;
  v_end := least(t.ends_at, p_ended_at);

  update team_questions
     set state = 'TIMED_OUT', timed_out_at = timer_deadline, timer_deadline = null
   where team_id = p_team_id and state = 'ACTIVE' and timer_deadline <= v_end;

  update teams set status = 'ENDED', ended_at = v_end where id = p_team_id;

  insert into audit_events (occurred_at, actor_kind, staff_id, team_id, event_type, entity_type, entity_id, payload)
  values (app.now(), case when p_staff_id is null then 'SYSTEM' else 'STAFF' end, p_staff_id, p_team_id,
          'TEAM_ENDED', 'TEAM', p_team_id::text,
          jsonb_build_object('reason', p_reason, 'ended_at', app.epoch_ms(v_end), 'ends_at', app.epoch_ms(t.ends_at)));
end $$;

-- ---------------------------------------------------------------------------------------------------------------
-- set_competition_status(staff_id, action, idempotency_key)        SUPER_ADMIN only
--   open   SETUP            → RUNNING   guard: ≥ 1 team, exactly 10 themes, 50 questions and exactly 5 questions in every theme
--   pause  RUNNING          → PAUSED
--   resume PAUSED           → RUNNING   every RUNNING team's ends_at and every ACTIVE question deadline shifts by the
--                                        paused duration; a team already past its end at the instant of the pause is
--                                        ended (ended_at = its scheduled end) instead of being revived by the shift
--   end    RUNNING/PAUSED   → ENDED     every RUNNING team is ended (reason COMPETITION_ENDED)
-- Asking for the state the competition is already in (open/resume when RUNNING, pause when PAUSED, end when ENDED) is an
-- idempotent no-op: same response shape, `changed: false`, no audit row, no version bump. Anything else is
-- INVALID_COMPETITION_TRANSITION. Every real change bumps competition.state_version and the state_version of every team
-- (the competition status is part of every team snapshot) and writes COMPETITION_STATUS_CHANGED.
-- ---------------------------------------------------------------------------------------------------------------
create function public.set_competition_status(p_staff_id uuid, p_action text, p_idem_key uuid) returns jsonb
language plpgsql security definer
set search_path = pg_catalog, public, extensions, app, pg_temp
as $$
declare
  v_now     timestamptz := app.now();
  v_comp    competition%rowtype;
  v_from    competition_status;
  v_to      competition_status;
  v_fp      text := 'action:' || coalesce(p_action, '');
  v_replay  jsonb;
  v_delta   interval := interval '0';
  v_shifted int := 0;
  v_ended   int := 0;
  v_ended_at timestamptz;
  v_team    teams%rowtype;
  v_teams   int;
  v_resp    jsonb;
begin
  if p_action is null or p_action not in ('open', 'pause', 'resume', 'end') then
    perform app.fail('VALIDATION_FAILED', jsonb_build_object('fields', jsonb_build_array('action')));
  end if;
  perform app.require_super_admin(p_staff_id);

  select * into v_comp from competition where id = 1 for update;     -- lock order: competition first
  if not found then
    perform app.fail('NOT_FOUND');
  end if;

  v_replay := app.idem_lookup(p_staff_id, p_idem_key, 'set_competition_status', v_fp);
  if v_replay is not null then
    return v_replay || '{"replayed": true}'::jsonb;
  end if;

  v_from := v_comp.status;
  v_to := case p_action when 'pause' then 'PAUSED' when 'end' then 'ENDED' else 'RUNNING' end::competition_status;

  if v_from = v_to then
    -- already there: idempotent no-op
    v_resp := jsonb_build_object('replayed', false, 'changed', false, 'action', p_action, 'from', v_from, 'to', v_to,
                                 'competition', app.competition_json());
    perform app.idem_store(p_staff_id, p_idem_key, 'set_competition_status', v_fp, v_resp);
    return v_resp;
  end if;

  if not ((p_action = 'open' and v_from = 'SETUP')
       or (p_action = 'pause' and v_from = 'RUNNING')
       or (p_action = 'resume' and v_from = 'PAUSED')
       or (p_action = 'end' and v_from in ('RUNNING', 'PAUSED'))) then
    perform app.fail('INVALID_COMPETITION_TRANSITION', jsonb_build_object('from', v_from, 'action', p_action));
  end if;

  if p_action = 'open' then
    -- the 10 × 5 shape is proved per theme, not only by the totals (10 themes and 50 questions in total could still be 4 + 6)
    if (select count(*) from teams) < 1
       or (select count(*) from themes) <> 10
       or (select count(*) from questions) <> 50
       or exists (select 1 from themes t where (select count(*) from questions q where q.theme_id = t.id) <> 5) then
      perform app.fail('COMPETITION_NOT_READY', jsonb_build_object(
        'teams', (select count(*) from teams), 'themes', (select count(*) from themes),
        'questions', (select count(*) from questions),
        'themes_not_five', (select count(*) from themes t where (select count(*) from questions q where q.theme_id = t.id) <> 5)));
    end if;
    update competition set status = 'RUNNING', opened_at = v_now where id = 1;

  elsif p_action = 'pause' then
    update competition set status = 'PAUSED', paused_at = v_now where id = 1;

  else
    perform 1 from teams order by id for update;                      -- then every team, in id order

    if p_action = 'resume' then
      v_delta := greatest(v_now - v_comp.paused_at, interval '0');
      -- A team whose scheduled end was already behind it when the pause began must not be revived by the shift.
      for v_team in select * from teams where status = 'RUNNING' and ends_at <= v_comp.paused_at order by id loop
        perform app.expire_team(v_team.id, 'TIMER', v_team.ends_at, p_staff_id);
        v_ended := v_ended + 1;
      end loop;
      update team_questions q
         set timer_deadline = q.timer_deadline + v_delta
        from teams t
       where q.team_id = t.id and t.status = 'RUNNING' and q.state = 'ACTIVE';
      with s as (update teams set ends_at = ends_at + v_delta where status = 'RUNNING' returning 1)
        select count(*) into v_shifted from s;
      update competition set status = 'RUNNING', paused_at = null where id = 1;

    else  -- end
      v_ended_at := case when v_from = 'PAUSED' then v_comp.paused_at else v_now end;
      for v_team in select * from teams where status = 'RUNNING' order by id loop
        perform app.expire_team(v_team.id, 'COMPETITION_ENDED', v_ended_at, p_staff_id);
        v_ended := v_ended + 1;
      end loop;
      update competition set status = 'ENDED', ended_at = v_now, paused_at = null where id = 1;
    end if;
  end if;

  update competition set state_version = state_version + 1 where id = 1;
  update teams set state_version = state_version + 1;
  select count(*) into v_teams from teams;

  insert into audit_events (occurred_at, actor_kind, staff_id, event_type, entity_type, entity_id, payload, request_id)
  values (v_now, 'STAFF', p_staff_id, 'COMPETITION_STATUS_CHANGED', 'COMPETITION', '1',
          jsonb_build_object('from', v_from, 'to', v_to, 'action', p_action,
                             'paused_seconds', case when p_action = 'resume' then floor(extract(epoch from v_delta)) end,
                             'teams_shifted', case when p_action = 'resume' then v_shifted end,
                             'teams_ended', case when p_action in ('resume', 'end') then v_ended end),
          p_idem_key);

  v_resp := jsonb_build_object(
    'replayed', false, 'changed', true, 'action', p_action, 'from', v_from, 'to', v_to,
    'paused_seconds', case when p_action = 'resume' then floor(extract(epoch from v_delta)) end,
    'teams_shifted', v_shifted, 'teams_ended', v_ended, 'teams_total', v_teams,
    'competition', app.competition_json());
  perform app.idem_store(p_staff_id, p_idem_key, 'set_competition_status', v_fp, v_resp);
  return v_resp;
end $$;

-- ---------------------------------------------------------------------------------------------------------------
-- start_team_competition(team_id, member_id, idempotency_key)      participant: "Enter competition"
-- Sets status = RUNNING, started_at = app.now(), ends_at = started_at + ultimate_seconds (7200, locked by a check
-- constraint) in ONE statement under the team lock, so concurrent members observe one pair of timestamps. Login never
-- calls it. A team that is already RUNNING returns its existing state untouched (no reset, no audit, no version bump),
-- whatever the competition status; the gate below applies only to an actual start.
--   Rejections: FORBIDDEN (member not in team) · COMPETITION_NOT_RUNNING (SETUP/ENDED) · COMPETITION_PAUSED ·
--               ALREADY_SUBMITTED (FINAL_SUBMITTED) · TEAM_ENDED (ENDED/DISQUALIFIED).
-- Result: { replayed, started_now, state: <team snapshot> }.
-- ---------------------------------------------------------------------------------------------------------------
create function public.start_team_competition(p_team_id uuid, p_member_id uuid, p_idem_key uuid) returns jsonb
language plpgsql security definer
set search_path = pg_catalog, public, extensions, app, pg_temp
as $$
declare
  v_now     timestamptz;
  v_team    teams%rowtype;
  v_comp    competition%rowtype;
  v_fp      text := 'member:' || coalesce(p_member_id::text, '');
  v_replay  jsonb;
  v_started boolean := false;
  v_resp    jsonb;
begin
  if p_team_id is null or p_member_id is null
     or not exists (select 1 from team_members where id = p_member_id and team_id = p_team_id) then
    perform app.fail('FORBIDDEN');                                     -- a member can only act for their own team
  end if;
  if p_idem_key is null then
    perform app.fail('VALIDATION_FAILED', jsonb_build_object('fields', jsonb_build_array('idempotencyKey')));
  end if;

  v_team := app.lock_team(p_team_id);                                  -- competition (share) → team (update)

  v_replay := app.idem_lookup(p_team_id, p_idem_key, 'start_team_competition', v_fp);
  if v_replay is not null then
    return v_replay || '{"replayed": true}'::jsonb;
  end if;

  select * into v_comp from competition where id = 1;

  if v_team.status <> 'RUNNING' then
    if v_comp.id is null or v_comp.status in ('SETUP', 'ENDED') then
      perform app.fail('COMPETITION_NOT_RUNNING');
    elsif v_comp.status = 'PAUSED' then
      perform app.fail('COMPETITION_PAUSED');
    end if;
    if v_team.status = 'FINAL_SUBMITTED' then
      perform app.fail('ALREADY_SUBMITTED');
    elsif v_team.status <> 'NOT_STARTED' then
      perform app.fail('TEAM_ENDED');                                  -- ENDED or DISQUALIFIED
    end if;

    v_now := app.now();
    update teams
       set status = 'RUNNING',
           started_at = v_now,
           ends_at = v_now + make_interval(secs => v_comp.ultimate_seconds),
           state_version = state_version + 1
     where id = p_team_id;

    insert into audit_events (occurred_at, actor_kind, member_id, team_id, event_type, entity_type, entity_id, payload, request_id)
    values (v_now, 'MEMBER', p_member_id, p_team_id, 'TEAM_STARTED', 'TEAM', p_team_id::text,
            jsonb_build_object('started_at', app.epoch_ms(v_now),
                               'ends_at', app.epoch_ms(v_now + make_interval(secs => v_comp.ultimate_seconds)),
                               'ultimate_seconds', v_comp.ultimate_seconds),
            p_idem_key);
    v_started := true;
  end if;

  v_resp := jsonb_build_object('replayed', false, 'started_now', v_started,
                               'state', app.team_state_json(p_team_id, p_member_id));
  perform app.idem_store(p_team_id, p_idem_key, 'start_team_competition', v_fp, v_resp);
  return v_resp;
end $$;

-- ---------------------------------------------------------------------------------------------------------------
-- get_team_state(team_id, member_id)      participant: the authoritative snapshot (a read; takes no lock)
-- ---------------------------------------------------------------------------------------------------------------
create function public.get_team_state(p_team_id uuid, p_member_id uuid) returns jsonb
language plpgsql stable security definer
set search_path = pg_catalog, public, extensions, app, pg_temp
as $$
begin
  if p_team_id is null or p_member_id is null
     or not exists (select 1 from team_members where id = p_member_id and team_id = p_team_id) then
    perform app.fail('FORBIDDEN');
  end if;
  return app.team_state_json(p_team_id, p_member_id);
end $$;

-- ---------------------------------------------------------------------------------------------------------------
-- Privileges. Explicit for every function above: no PUBLIC, no anon, no authenticated; service_role only.
-- ---------------------------------------------------------------------------------------------------------------
revoke all on function app.fail(text, jsonb)                                         from public, anon, authenticated;
revoke all on function app.epoch_ms(timestamptz)                                     from public, anon, authenticated;
revoke all on function app.require_super_admin(uuid)                                 from public, anon, authenticated;
revoke all on function app.lock_team(uuid)                                           from public, anon, authenticated;
revoke all on function app.idem_lookup(uuid, uuid, text, text)                       from public, anon, authenticated;
revoke all on function app.idem_store(uuid, uuid, text, text, jsonb)                 from public, anon, authenticated;
revoke all on function app.team_state_json(uuid, uuid)                               from public, anon, authenticated;
revoke all on function app.competition_json()                                        from public, anon, authenticated;
revoke all on function app.expire_team(uuid, text, timestamptz, uuid)                from public, anon, authenticated;
revoke all on function public.set_competition_status(uuid, text, uuid)               from public, anon, authenticated;
revoke all on function public.start_team_competition(uuid, uuid, uuid)               from public, anon, authenticated;
revoke all on function public.get_team_state(uuid, uuid)                             from public, anon, authenticated;

grant execute on function app.fail(text, jsonb)                                         to service_role;
grant execute on function app.epoch_ms(timestamptz)                                     to service_role;
grant execute on function app.require_super_admin(uuid)                                 to service_role;
grant execute on function app.lock_team(uuid)                                           to service_role;
grant execute on function app.idem_lookup(uuid, uuid, text, text)                       to service_role;
grant execute on function app.idem_store(uuid, uuid, text, text, jsonb)                 to service_role;
grant execute on function app.team_state_json(uuid, uuid)                               to service_role;
grant execute on function app.competition_json()                                        to service_role;
grant execute on function app.expire_team(uuid, text, timestamptz, uuid)                to service_role;
grant execute on function public.set_competition_status(uuid, text, uuid)               to service_role;
grant execute on function public.start_team_competition(uuid, uuid, uuid)               to service_role;
grant execute on function public.get_team_state(uuid, uuid)                             to service_role;
