#!/usr/bin/env node
// Generates every derived copy of the official competition content from ONE source:
//
//   content/concetto26/official-content.json            (the source of truth; extracted from the official .docx)
//     -> supabase/migrations/20261006000019_official_content.sql   (the database rows: themes, questions, hints, rewards)
//     -> src/lib/content/official-public.ts                        (PUBLIC text only: theme names/descriptions and the rules)
//
//   node scripts/content/generate.mjs           write the two files
//   node scripts/content/generate.mjs --check   fail (exit 1) when either file differs from what the source produces
//
// Questions, hints and rewards are never written to anything the browser can import: only the migration carries them.
// The output is deterministic (no timestamps, no randomness): the same JSON always gives the same bytes.
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

import * as prettier from "prettier";

const root = resolve(import.meta.dirname, "../..");
const SOURCE = join(root, "content/concetto26/official-content.json");
const MIGRATION = join(root, "supabase/migrations/20261006000019_official_content.sql");
const PUBLIC_TS = join(root, "src/lib/content/official-public.ts");

const THEME_CODES = [..."ABCDEFGHIJ"];

/** Throws unless the source is exactly the shape the importer relies on. */
export function validate(c) {
  const fail = (m) => {
    throw new Error(`official-content.json: ${m}`);
  };
  if (c.themes.length !== 10) fail("expected 10 themes");
  c.themes.forEach((t, i) => {
    if (t.id !== THEME_CODES[i]) fail(`theme ${i + 1} must be ${THEME_CODES[i]}`);
    if (!t.name?.trim() || !t.description?.trim())
      fail(`theme ${t.id} needs a name and description`);
  });
  if (c.questions.length !== 50) fail("expected 50 questions");
  c.questions.forEach((q, i) => {
    const theme = THEME_CODES[Math.floor(i / 5)];
    const ordinal = (i % 5) + 1;
    if (q.id !== `${theme}.${ordinal}` || q.theme !== theme || q.ordinal !== ordinal)
      fail(`question ${i + 1} must be ${theme}.${ordinal}`);
    for (const k of ["question", "hint1", "hint2"])
      if (typeof q[k] !== "string" || !q[k].trim()) fail(`${q.id} has an empty ${k}`);
    if (!(Number.isInteger(q.reward) && q.reward >= 0))
      fail(
        `${q.id} needs a reward (a non-negative integer): a fresh database cannot be installed without one`,
      );
  });
  if (c.rules.length !== 8) fail("expected 8 rules");
  c.rules.forEach((r, i) => {
    if (r.number !== i + 1 || !r.text?.trim()) fail(`rule ${i + 1} is out of order or empty`);
  });
}

const questionId = (code, ordinal) => THEME_CODES.indexOf(code) * 5 + ordinal; // questions.id = (theme - 1) * 5 + ordinal
const hintId = (qid, tier) => (qid - 1) * 2 + tier; // hints.id, as in supabase/seed.sql

function sqlText(s) {
  if (s.includes("$c26$")) throw new Error("content contains the SQL quote tag $c26$");
  return `$c26$${s}$c26$`;
}

function migrationSql(c, sourceSha) {
  const themes = c.themes
    .map((t, i) => `    (${i + 1}, ${sqlText(t.name)}, ${sqlText(t.description)})`)
    .join(",\n");
  const questions = c.questions
    .map((q) => `    (${questionId(q.theme, q.ordinal)}, ${sqlText(q.question)}, ${q.reward})`)
    .join(",\n");
  const hints = c.questions
    .flatMap((q) => {
      const id = questionId(q.theme, q.ordinal);
      return [1, 2].map(
        (tier) => `    (${hintId(id, tier)}, ${sqlText(tier === 1 ? q.hint1 : q.hint2)})`,
      );
    })
    .join(",\n");

  return `-- B17 / migration 19 — official Concetto 26 content: 10 themes, 50 questions, 100 hints and the per-question rewards.
--
-- GENERATED by scripts/content/generate.mjs from content/concetto26/official-content.json (content JSON sha256 ${sourceSha}).
-- Do not edit by hand: change the JSON and regenerate (\`node scripts/content/generate.mjs\`; \`--check\` verifies it).
--
-- Order of events this migration has to be right for (Supabase runs migrations FIRST and supabase/seed.sql AFTER them on
-- \`supabase db reset\` / \`supabase start\`; \`supabase db push\` runs no seed unless --include-seed, which is also after):
--
--   A. UPGRADE of an existing database (production at B16): the 10 / 50 / 100 content rows already exist. Only their CONTENT
--      columns are overwritten:  themes.name, themes.description · questions.body_md, questions.reward_coins · hints.body_md.
--   B. FRESH database: the content tables are still EMPTY when this migration runs (the seed has not run yet). The official rows are
--      INSTALLED here, with the same structure the seed gives its rows (see "structure" below). When supabase/seed.sql runs after
--      it, every one of its content inserts is ON CONFLICT DO NOTHING, so the official text is kept; the seed still adds what is
--      not content (buy-time options, reviewer-key placeholders).
--   C. Any other shape (not exactly 0/0/0 or 10/50/100 rows) aborts the migration with nothing changed.
--
-- Structure of an installed row = what supabase/seed.sql gives it: difficulty EASY for themes 1-3, MEDIUM 4-7, HARD 8-10 (a question
-- has its theme's), unlock cost 100, display order = theme number, topics {placeholder}, question time limit 240 s, hint cost 20 / 40.
-- A test (b17_fresh.upgrade.mjs) installs both ways and fails if any structural column differs.
--
-- What it never touches: any team, member, session, team_themes / team_questions / answer_drafts / submissions row, coin balance,
-- ledger entry, timer, hint purchase, final score, penalty, or any price/duration/ordering column of an existing row (unlock_cost,
-- hints.cost, buy-time options, time_limit_seconds, difficulty, topics, ids). approve_submission and every other function are
-- unchanged: approval already pays exactly questions.reward_coins once (ledger index ctx_reward), so rewards are data.
--
-- Safe to re-run: only rows whose content differs are updated; a second run changes nothing and writes no audit row. An UPGRADE writes one
-- CONTENT_IMPORTED audit event (mode 'updated'); the first install into an empty database writes none (a fresh database has an empty audit log).
-- Submissions already approved keep the reward_awarded they were paid; a submission still PENDING when this runs is paid the NEW
-- reward of its question when it is approved. Apply it before the competition opens, or when no review is pending.

do $c26_import$
declare
  v_themes    int;
  v_questions int;
  v_hints     int;
  n_themes    int;
  n_questions int;
  n_hints     int;
  v_mode      text;
begin
  select count(*) into v_themes from themes;
  select count(*) into v_questions from questions;
  select count(*) into v_hints from hints;

  if not ((v_themes = 0 and v_questions = 0 and v_hints = 0) or (v_themes = 10 and v_questions = 50 and v_hints = 100)) then
    raise exception 'official content: expected 10 themes, 50 questions and 100 hints, found %, % and % (an empty database is also accepted)',
      v_themes, v_questions, v_hints;
  end if;

  -- the official content, once, for both paths
  create temp table c26_themes (id smallint primary key, name text not null, description text not null) on commit drop;
  create temp table c26_questions (id smallint primary key, body_md text not null, reward_coins int not null) on commit drop;
  create temp table c26_hints (id smallint primary key, body_md text not null) on commit drop;

  insert into c26_themes (id, name, description) values
${themes};

  insert into c26_questions (id, body_md, reward_coins) values
${questions};

  insert into c26_hints (id, body_md) values
${hints};

  if v_themes = 0 then
    v_mode := 'installed';

    insert into themes (id, code, name, description, topics, difficulty, unlock_cost, display_order)
    select c.id, chr(64 + c.id), c.name, c.description, array['placeholder'],
           (case when c.id <= 3 then 'EASY' when c.id <= 7 then 'MEDIUM' else 'HARD' end)::difficulty,
           100, c.id
      from c26_themes c;
    get diagnostics n_themes = row_count;

    insert into questions (id, theme_id, ordinal, body_md, difficulty, reward_coins, time_limit_seconds)
    select q.id, (q.id - 1) / 5 + 1, (q.id - 1) % 5 + 1, q.body_md, t.difficulty, q.reward_coins, 240
      from c26_questions q
      join themes t on t.id = (q.id - 1) / 5 + 1;
    get diagnostics n_questions = row_count;

    insert into hints (id, question_id, tier, body_md, cost)
    select h.id, (h.id + 1) / 2, (h.id - 1) % 2 + 1, h.body_md,
           case (h.id - 1) % 2 + 1 when 1 then 20 else 40 end
      from c26_hints h;
    get diagnostics n_hints = row_count;
  else
    v_mode := 'updated';

    update themes t
       set name = c.name, description = c.description
      from c26_themes c
     where t.id = c.id
       and (t.name, t.description) is distinct from (c.name, c.description);
    get diagnostics n_themes = row_count;

    update questions q
       set body_md = c.body_md, reward_coins = c.reward_coins
      from c26_questions c
     where q.id = c.id
       and (q.body_md, q.reward_coins) is distinct from (c.body_md, c.reward_coins);
    get diagnostics n_questions = row_count;

    update hints h
       set body_md = c.body_md
      from c26_hints c
     where h.id = c.id
       and h.body_md is distinct from c.body_md;
    get diagnostics n_hints = row_count;
  end if;

  -- whichever way it went, the database now holds exactly the official content
  if (select count(*) from themes t join c26_themes c using (id)
       where (t.name, t.description) = (c.name, c.description)) <> 10
     or (select count(*) from questions q join c26_questions c using (id)
          where (q.body_md, q.reward_coins) = (c.body_md, c.reward_coins)) <> 50
     or (select count(*) from hints h join c26_hints c using (id)
          where h.body_md = c.body_md) <> 100 then
    raise exception 'official content: the database does not hold the official content after the import';
  end if;

  -- an UPDATE of existing rows is an operational change and is audited; the first INSTALL into an empty database is the database's
  -- initial content (like the seed itself) and writes no audit row, so a freshly built database has an empty audit log
  if v_mode = 'updated' and n_themes + n_questions + n_hints > 0 then
    insert into audit_events (occurred_at, actor_kind, event_type, entity_type, entity_id, payload)
    values (clock_timestamp(), 'SYSTEM', 'CONTENT_IMPORTED', 'COMPETITION', '1',
            jsonb_build_object('mode', v_mode, 'themes_changed', n_themes, 'questions_changed', n_questions,
                               'hints_changed', n_hints, 'content_sha256', '${sourceSha}'));
  end if;
  raise notice 'official content: % themes, % questions, % hints updated (%)', n_themes, n_questions, n_hints, v_mode;

  drop table c26_themes;
  drop table c26_questions;
  drop table c26_hints;
end $c26_import$;
`;
}

function publicTs(c) {
  const themes = c.themes.map((t) => ({ id: t.id, name: t.name, description: t.description }));
  const rules = c.rules.map((r) => r.text);
  return `// GENERATED by scripts/content/generate.mjs from content/concetto26/official-content.json — do not edit by hand.
// Public competition text only (theme names/descriptions and the rules). Questions, hints and rewards are deliberately NOT
// here: they exist only in the database (supabase/migrations/20261006000019_official_content.sql) and reach a team only
// through the server, when the team is entitled to them.

export const OFFICIAL_THEMES = ${JSON.stringify(themes, null, 2)} as const;

export const OFFICIAL_RULES = ${JSON.stringify(rules, null, 2)} as const;
`;
}

export async function build() {
  const raw = readFileSync(SOURCE, "utf8");
  const content = JSON.parse(raw);
  validate(content);
  const sourceSha = createHash("sha256").update(raw).digest("hex");
  const config = (await prettier.resolveConfig(PUBLIC_TS)) ?? {};
  const ts = await prettier.format(publicTs(content), { ...config, filepath: PUBLIC_TS });
  return [
    [MIGRATION, migrationSql(content, sourceSha)],
    [PUBLIC_TS, ts],
  ];
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const check = process.argv.includes("--check");
  const files = await build();
  let stale = 0;
  for (const [path, text] of files) {
    if (check) {
      let current = null;
      try {
        current = readFileSync(path, "utf8");
      } catch {
        /* missing counts as stale */
      }
      if (current !== text) {
        stale++;
        console.error(`stale: ${path.replace(`${root}/`, "")}`);
      }
    } else {
      writeFileSync(path, text);
      console.log(`wrote ${path.replace(`${root}/`, "")}`);
    }
  }
  if (check) {
    if (stale) {
      console.error("run: node scripts/content/generate.mjs");
      process.exit(1);
    }
    console.log("content: generated files are up to date");
  }
}
