-- B17 / migration 19 — official Concetto 26 content: 10 themes, 50 questions, 100 hints and the per-question rewards.
--
-- GENERATED by scripts/content/generate.mjs from content/concetto26/official-content.json (content JSON sha256 1c2133dd052a901aa6c9eae4fc2b418fa33b55b55ad9ffa7b4a423b16d17dcdb).
-- Do not edit by hand: change the JSON and regenerate (`node scripts/content/generate.mjs`; `--check` verifies it).
--
-- Order of events this migration has to be right for (Supabase runs migrations FIRST and supabase/seed.sql AFTER them on
-- `supabase db reset` / `supabase start`; `supabase db push` runs no seed unless --include-seed, which is also after):
--
--   A. UPGRADE of an existing database (production at B16): the 10 / 50 / 100 content rows already exist. Only their CONTENT
--      columns are overwritten:  themes.name, themes.description · questions.body_md, questions.reward_coins · hints.body_md.
--   B. FRESH database: the content tables are still EMPTY when this migration runs (the seed has not run yet). The official rows are
--      INSTALLED here, with the same structure the seed gives its rows (see "structure" below). When supabase/seed.sql runs after
--      it, every one of its content inserts is ON CONFLICT DO NOTHING, so the official text is kept; the seed still adds what is
--      not content (buy-time options, reviewer-key placeholders).
--   C. Any other shape (not exactly 0/0/0 or 10/50/100 rows) aborts the migration with nothing changed.
--
-- Structure of an installed row = what supabase/seed.sql gives it: difficulty EASY for themes 1-3, MEDIUM 4-7, HARD 8-10 (a question
-- has its theme's), unlock cost 100, display order = theme number, topics {placeholder}, question time limit 240 s, hint cost 20 / 40.
-- A test (b17_fresh.upgrade.mjs) installs both ways and fails if any structural column differs.
--
-- What it never touches: any team, member, session, team_themes / team_questions / answer_drafts / submissions row, coin balance,
-- ledger entry, timer, hint purchase, final score, penalty, or any price/duration/ordering column of an existing row (unlock_cost,
-- hints.cost, buy-time options, time_limit_seconds, difficulty, topics, ids). approve_submission and every other function are
-- unchanged: approval already pays exactly questions.reward_coins once (ledger index ctx_reward), so rewards are data.
--
-- Safe to re-run: only rows whose content differs are updated; a second run changes nothing and writes no audit row. An UPGRADE writes one
-- CONTENT_IMPORTED audit event (mode 'updated'); the first install into an empty database writes none (a fresh database has an empty audit log).
-- Submissions already approved keep the reward_awarded they were paid; a submission still PENDING when this runs is paid the NEW
-- reward of its question when it is approved. Apply it before the competition opens, or when no review is pending.

do $c26_import$
declare
  v_themes    int;
  v_questions int;
  v_hints     int;
  n_themes    int;
  n_questions int;
  n_hints     int;
  v_mode      text;
begin
  select count(*) into v_themes from themes;
  select count(*) into v_questions from questions;
  select count(*) into v_hints from hints;

  if not ((v_themes = 0 and v_questions = 0 and v_hints = 0) or (v_themes = 10 and v_questions = 50 and v_hints = 100)) then
    raise exception 'official content: expected 10 themes, 50 questions and 100 hints, found %, % and % (an empty database is also accepted)',
      v_themes, v_questions, v_hints;
  end if;

  -- the official content, once, for both paths
  create temp table c26_themes (id smallint primary key, name text not null, description text not null) on commit drop;
  create temp table c26_questions (id smallint primary key, body_md text not null, reward_coins int not null) on commit drop;
  create temp table c26_hints (id smallint primary key, body_md text not null) on commit drop;

  insert into c26_themes (id, name, description) values
    (1, $c26$DIG INTO THE PASSWORD OF IIT ISM$c26$, $c26$ADVANCED CRYPTOGRAPHY, NUMBER THEORY & COMBINATORICS$c26$),
    (2, $c26$HOW BAD CAN BE HOSTEL FOOD$c26$, $c26$PROBABILITY, STATISTICS, OPTIMIZATION AND QUEUING THEORY$c26$),
    (3, $c26$END SEM FEAR TAKEOVER$c26$, $c26$Engineering Mathematics, Calculus, and Differential Equations$c26$),
    (4, $c26$WHAT IS THE SIZE OF THE CAMPUS?$c26$, $c26$Geometry, Distance and Measurement, and Coordinate Geometry$c26$),
    (5, $c26$WHO IS THE POKER GUY HERE$c26$, $c26$Probability, Combinatorics, Game Theory, and Derangements$c26$),
    (6, $c26$ASK OUT YOUR CRUSH$c26$, $c26$PROBABILITY AND STATISTICS$c26$),
    (7, $c26$I WANT A STRAIGHT TRAJECTORY IN LIFE$c26$, $c26$Linear Systems, Geometry, Infinite Products, and Integrals$c26$),
    (8, $c26$IS THE GUARD CHASING YOU?$c26$, $c26$Coordinate Geometry, Conics, Vectors, and Relative Motion$c26$),
    (9, $c26$WHAT AMOUNT TO PUT IN PAY REQUEST TO MY SENIORS$c26$, $c26$Probability, Optimization, Geometric Distributions, and Game Theory$c26$),
    (10, $c26$DO YOU HATE PROVING YOURSELF?$c26$, $c26$Mathematical proofs, logic, induction, and contradiction$c26$);

  insert into c26_questions (id, body_md, reward_coins) values
    (1, $c26$A message intercepted from the campus network has been encoded in two steps. First, remove all spaces and punctuation from the plaintext, convert each letter to a number using A = 0, B = 1, …, Z = 25, and replace each value x by (x + 7) mod 26. Then reverse the order of the resulting letters.
The intercepted ciphertext is:
    PHOHOHYHHHGHTBFR

Recover the original message and write it in uppercase with the original word spacing restored.$c26$, 100),
    (2, $c26$A client and server use a small demonstration setup to recover a session token.

Part A: Diffie–Hellman
The server’s public value is B = 8, the client’s private exponent is a = 6, and the prime modulus is p = 23. Compute the shared value K = B^a mod p.

Part B: RSA decryption
The RSA modulus is N = 55 and the private exponent is d = 27. The intercepted ciphertext is C = 12. Compute the recovered token T = C^d mod N.

Give your final answer as two comma-separated integers: K,T.$c26$, 100),
    (3, $c26$A critical network router processes an array of N = 12 data packets. Due to buffer limits, the router can drop packets, but it cannot drop two consecutive packets (i.e., in a binary status sequence of length N where 1 = processed and 0 = dropped, the pattern '00' is forbidden).

Tasks:
1. Define the dynamic programming state transitions dp[i][0] (number of valid sequences of length i ending in 0) and dp[i][1] (ending in 1).
2. Derive the unified scalar recurrence relation f(n) for total valid configurations of length n.
3. Compute f(12) step-by-step from base cases f(0) and f(1).
4. If the constraint is modified such that no three consecutive packets can be dropped (forbidden pattern '000'), derive the new linear recurrence relation and compute the number of valid sequences for N = 6.$c26$, 100),
    (4, $c26$An array A of size N = 1000 represents millisecond network delay spikes generated by:

    A[i] = (i^2 + 3*i) (mod 50)   for 1 <= i <= 1000

A sequence of contiguous packets A[i...j] (1 <= i <= j <= 1000) causes buffer overflow if its sum is evenly divisible by S = 2008.

Tasks:
1. Define the prefix sum sequence P[m] = sum_{k=1}^m A[k] with P[0] = 0. Show why the condition sum_{k=i}^j A[k] = 0 (mod S) is logically equivalent to P[j] = P[i-1] (mod S).
2. Let C_r be the frequency of index m in [0, 1000] such that P[m] = r (mod S). Express the total number of valid contiguous subarrays W as a combinatorial summation over C_r.
3. Explain why this approach reduces time complexity from O(N^2) brute force to O(N + S), detailing how combination pairs C(C_r, 2) count disjoint index intervals.$c26$, 100),
    (5, $c26$A campus data center routes traffic from n = 6 input lines {L1, L2, L3, L4, L5, L6} to n = 6 output ports {P1, P2, P3, P4, P5, P6} such that each line maps to a distinct port (a permutation pi in S6).

To prevent hardware feedback loops, the mapping has the following positional restrictions:
  • Standard Derangement: Line Li cannot map to Port Pi for all 1 <= i <= 6 (pi(i) != i).
  • Additional Firewalls: Line L1 cannot map to Port P2 (pi(1) != 2), and Line L2 cannot map to Port P3 (pi(2) != 3).

Tasks:
1. State the Principle of Inclusion-Exclusion (PIE) formula for counting permutations with forbidden positions.
2. Define the set of forbidden condition properties A = {r1, r2, r3, r4, r5, r6, r7, r8}, where r1...r6 correspond to pi(i) = i, r7 corresponds to pi(1) = 2, and r8 corresponds to pi(2) = 3.
3. Determine the number of valid non-conflicting routing configurations by evaluating the intersection sizes |A_i1 cap A_i2 cap ... cap A_ik|.$c26$, 100),
    (6, $c26$The hostel mess has one serving counter. Students arrive according to a Poisson process at 20 students per hour. A fast plate takes exactly 1 minute and is chosen with probability q; a full thali takes exactly 3 minutes and is chosen with probability 1 − q. The cook currently uses q = 0.5. Find the mean time, in minutes, that a student waits in the queue, excluding service, in steady state.$c26$, 70),
    (7, $c26$Using q = 0.5, find the expected sum of the queue-waiting times of all students served during one busy period. A busy period begins when a student arrives at an empty counter and ends when the counter next becomes empty.$c26$, 70),
    (8, $c26$The warden defines the dissatisfaction cost per student as D(q) = Wq(q) + 4q, where the 4q term penalizes complaints about the fast plate being “just dal-rice.” The cook may choose any q in (0, 1], with the arrival rate unchanged. Find the total reduction in dissatisfaction per hour when the cook changes from q = 0.5 to the optimal q.$c26$, 90),
    (9, $c26$Each dinner is independently bad with probability 1/3 and good with probability 2/3. Find the expected number of days until the pattern bad, good, bad (B-G-B) appears for the first time as three consecutive dinners.$c26$, 60),
    (10, $c26$The mess committee surveys satisfaction scores in two hostels using stratified sampling. Hostel A has student share Wₐ = 0.4, standard deviation Sₐ = 5, and interview cost ₹1. Hostel B has student share Wᵦ = 0.6, standard deviation Sᵦ = 5, and interview cost ₹4. With a total budget of ₹256 and ignoring finite population correction, find the minimum possible variance of the weighted-mean estimator.$c26$, 100),
    (11, $c26$For each positive integer n, let Pₙ = ∏ₖ₌₁ⁿ(1 + tan(kπ/(4n))). Define I = limₙ→∞ (π/(4n)) ln Pₙ. Find a = 64I/(π ln 2).$c26$, 70),
    (12, $c26$Using the value of a from Q3.1, find b = Σₙ₌₁^∞ n^(a/2)/2ⁿ.$c26$, 80),
    (13, $c26$Find c = (120/(11e)) limₓ→₀ [((1 + x)^(1/x) − e + ex/2)/x²].$c26$, 80),
    (14, $c26$Let M be a c × c matrix whose entries are mᵢⱼ = |i − j|. Find d = det(M), using the value of c obtained in QC.3.$c26$, 90),
    (15, $c26$Evaluate L = limₙ→∞ n ∫₀¹ xⁿ(x² + 2)e^(x²) dx. Find L/e.$c26$, 90),
    (16, $c26$On Independence Day, a flagpole is tilted. Its line is given by (x+1)/0 = (y−2)/4 = z/3. Find the angle through which it must be rotated about the z-axis to make it vertical.$c26$, 100),
    (17, $c26$A bank near the heritage building is at (−13, −14, 0). The straightened pole-plus-flag is 15 m long. Assume the point (−1, 2, 0) on the pole’s line is at ground level, and the pole’s direction vector is (0, 4, 3). Find the equation of the line of sight from the bank to the top of the pole.$c26$, 60),
    (18, $c26$The oval garden near the heritage building is elliptical, centred at the origin. Its semi-major axis is 25 m along the x-axis and its semi-minor axis is 15 m along the y-axis. A coach standing at (30, 12, 0) kicks a football in a straight line parallel to the negative x-axis. The football travels until it reaches the boundary of the garden. Find the coordinates of the point where the football reaches the garden boundary.$c26$, 90),
    (19, $c26$Using the stopping point obtained in Q4.3, find its eccentric angle θ on the ellipse.$c26$, 50),
    (20, $c26$Find the distance between the centre of the ellipse and the stopping point from Q4.3. Treat this distance as the radius of a circular sector with central angle 30°. Find the sector area to 2 decimal places.$c26$, 90),
    (21, $c26$You are dealt 2 hole cards from a fresh 52-card deck. Let the probability that you are dealt a pocket pair be represented as a reduced fraction p/q. Find the value of q − p.$c26$, 70),
    (22, $c26$You are dealt 2 hole cards from a fresh 52-card deck. Let the probability that both your hole cards belong to the exact same suit be represented as a reduced fraction p/q. Find the value of p + q.$c26$, 80),
    (23, $c26$Two poker players, A and B, play a simplified zero-sum betting game. Player A chooses Bluff (B) or Play Safe (S), while Player B simultaneously chooses Call (C) or Fold (F). The payoff matrix gives Player A’s net payoff in coins; Player B receives the negative of this payoff.

                         Player B
                   Call (C)     Fold (F)
Player A  Bluff (B)      −4           6
          Play Safe (S)   3          −2

Both players may use mixed strategies. Let p be the probability that Player A bluffs and q be the probability that Player B calls. Find 300(p + q) when both players use optimal mixed strategies.$c26$, 90),
    (24, $c26$You hold Pocket Aces (A OF SPADES, A OF HEARTS). There are two opponents left to act behind you, and each receives 2 random hole cards. Let the probability that at least one of these two opponents is dealt a pocket pair of Aces or Kings be represented as a reduced fraction p/q. Find the value of p + q.$c26$, 60),
    (25, $c26$At a showdown, four unique cards of completely distinct ranks—an Ace, King, Queen, and Jack—are left exposed on the table. The dealer collects these 4 specific cards, shuffles them thoroughly, and redistributes them randomly into 4 distinct positions face-down on the table (Position 1 for Ace, Position 2 for King, Position 3 for Queen, Position 4 for Jack). If the probability that none of the 4 cards ends up back in its original designated position is expressed as a reduced fraction p/q, find the value of p + q.$c26$, 100),
    (26, $c26$To talk to your crush during a lecture, you sit in a row containing 15 seats. You place items on S seats to guarantee that no matter which unoccupied seat your crush chooses, they are forced to sit directly adjacent to at least one of your items. If S is the minimum number of seats needed, and P is the integer formed by concatenating your chosen 1-indexed seat positions in ascending order, what is P?$c26$, 70),
    (27, $c26$Using S = 5 from Question 1, you analyze your crush’s 10S + 1 = 51 friends who belong to K distinct campus clubs. What is the minimum value K_min such that you can guarantee at least two clubs have the exact same number of friends?$c26$, 70),
    (28, $c26$Using K = 11 from Question 2, you and your crush independently select 3 distinct days from an 11-day campus festival schedule. The probability that your selected schedules overlap on at least 2 days is an irreducible fraction a/b. Find a + b.$c26$, 90),
    (29, $c26$At your meet-up on day a + b of the semester, you order coffee together. Customers arrive at the café according to a Poisson process at an average rate λ = a + b per hour. If X is the number of arrivals in a 1-hour span, find E[X²].$c26$, 90),
    (30, $c26$Your crush presents a statistical challenge to deliver their final response. Their response score Y follows a Normal distribution N(μ, σ²), with mean μ equal to the answer from Question 4 and variance σ² = 2500 (so σ = 50). If P(Y ≤ y) = 0.9772 and the standard normal CDF satisfies Φ(2) = 0.9772, find y.$c26$, 100),
    (31, $c26$A vector-valued function w(t) satisfies w′(t) = Xw(t), where X = [[0, −2], [1/2, 0]] and w(0) = (2, 0). Find the maximum value of ‖w(t + π/2) − w(t)‖² over all real t.$c26$, 80),
    (32, $c26$The trajectory from Q8.1 traces an ellipse. Take the four points at times T, T + π/2, T + π, and T + 3π/2, and join them in order to form a quadrilateral. Using the ellipse enclosed by the trajectory as the reference shape, find the percentage of the ellipse’s area missed by the quadrilateral, rounded down to the nearest integer. (The result is independent of T.)$c26$, 90),
    (33, $c26$Evaluate the infinite product ∏ from n = 2 to ∞ of (n³ − 1)/(n³ + 1). Express your answer as a reduced fraction.$c26$, 90),
    (34, $c26$Evaluate the improper integral ∫ from 0 to 1 of ln(1 − x)/x dx.$c26$, 50),
    (35, $c26$Let F(x, y, z) = ln(1 − xyz)/(xyz), interpreted by continuity wherever xyz = 0. Evaluate the triple integral of F over the unit cube 0 ≤ x, y, z ≤ 1. If the result is written as −ζ(n), find n.$c26$, 100),
    (36, $c26$A circular zone is given by x² + y² = 16, and an escape parabola is given by y² = 16√2 x. The guard starts at the topmost point of the circle and moves anticlockwise along the circle to the point where the common tangent with positive slope to the circle and parabola touches the circle. He then follows this tangent to the portal on the parabola. Find the total distance travelled along the circular arc and then along the tangent. If the distance is aπ + b, enter a + b. Portal transit time: 1.5 seconds to enter and 1.5 seconds to exit.$c26$, 70),
    (37, $c26$The portal leads to an elliptical chamber given by (x − 17)²/25 + (y − 96/5)²/16 = 1. The guard appears at the lower endpoint of the right latus rectum of the ellipse. The runner is at the bottommost point of the original circle from Q9.1. At this instant, the guard moves with velocity v_G = −3i − 4j m/s and the runner moves with velocity v_R = −i − 2j m/s. Find the area of the triangle formed by the runner’s initial position, the guard’s initial position, and their meeting point.$c26$, 90),
    (38, $c26$The guard moves around the original circle with angular velocity π/2 rad/s anticlockwise and travels along the common tangent at 1 m/s. The portal takes 1.5 seconds to enter and 1.5 seconds to exit. Assume the runner remains at the bottommost point of the original circle until the guard exits the portal. After the guard exits, both move with the velocities given in Q9.2. Using the results from the previous questions, find the total time in seconds from the beginning of the chase until the guard catches the runner.$c26$, 90),
    (39, $c26$The guard is initially at G = (0, 0) and can run at a constant speed of 13 m/s in any direction. The runner is initially at R = (30, 0) and moves with velocity v_R = −5i + 12j m/s. After how many seconds will the guard catch the runner?$c26$, 90),
    (40, $c26$A circular security barrier is given by (x − 5)² + (y + 2)² = 169. The guard stands at G = (20, −7), outside the barrier. He fires a straight tracking beam along the line 3x + 4y = 32. The beam enters the circular barrier at one point and exits at another. Find the distance between the entry and exit points.$c26$, 100),
    (41, $c26$Senior i accepts a request of ₹x with probability 1 − x/kᵢ, independently, where (k₁, k₂, k₃, k₄) = (150, 200, 250, 300) for A, B, C, D. You send ₹50 to each of them. Given that exactly two accepted, what is the probability that A is one of the two?$c26$, 90),
    (42, $c26$You request ₹x₁, ₹x₂, ₹x₃, ₹x₄ from A, B, C, D with x₁ + x₂ + x₃ + x₄ = 500 and 0 ≤ xᵢ ≤ kᵢ. Senior i accepts independently with probability 1 − xᵢ/kᵢ, where (k₁, k₂, k₃, k₄) = (150, 200, 250, 300) (a larger kᵢ means a richer senior, who tolerates larger requests). Find the maximum possible expected total receipt.$c26$, 100),
    (43, $c26$Each day, A, B, C, D independently call you with probabilities 1/2, 1/3, 1/4, 1/5, independently across days. What is the probability that the first day on which you get at least one call is an odd-numbered day?$c26$, 80),
    (44, $c26$A, B, C, D independently ask you to run an errand with probabilities 1/2, 1/2, 3/4, 3/4, and the errands take 10, 20, 30, 40 minutes respectively. Let X be the total time spent on errands in a day. Find P(X ≥ 60).$c26$, 80),
    (45, $c26$To settle your pay requests, the seniors put 14 ₹10 notes into three labelled envelopes (a, b, c), none empty, so (1,6,7) and (6,1,7) are different splits. You and a senior take turns removing any number of notes from one envelope, and whoever takes the last note wins the pay request off the table. You move second and both play optimally. If you win for exactly k of the possible splits, shift each letter of EJKNN JCK forward by k places (Z wraps to A). With A = 1, B = 2, …, Z = 26, find the sum of the alphabet positions of all letters in the decoded message.$c26$, 100),
    (46, $c26$Person k (k = 1, 2, …, 2026) says: “Exactly k of the 2026 people here are liars.” Truth-tellers always tell the truth and liars always lie. Find the sum of the labels of all truth-tellers.$c26$, 80),
    (47, $c26$2025 people sit around a circular table. Each is either a truth-teller (always true) or a liar (always false). Every person says: “My two neighbours are of different types.” What is the maximum possible number of truth-tellers?$c26$, 90),
    (48, $c26$Three students each claim a statement holds for all positive integers n:
Alice: n² + n + 41 is prime (she also allows n = 0).
Bob: 2ⁿ ≥ n².
Carol: n³ + 2n is divisible by 3.
Let A be the smallest n where Alice’s claim fails and B the smallest n where Bob’s claim fails. Find A + B. (If Carol’s claim fails, add 1000. Otherwise add nothing.)$c26$, 70),
    (49, $c26$Josephus Problem
• n people stand in a circle, numbered from 1 to n in a clockwise direction.
• Starting from person 1, you count around the circle and eliminate every k-th person.
• The circle shrinks as people are removed, and counting continues from the next living person.
• This process repeats until only one person remains—the goal is to find the starting position of that last survivor.
There are 50 soldiers in a circle, ranked 1 to 50. Soldier 1 jumps first, then every alternate remaining soldier jumps. What is the rank of the last soldier?$c26$, 90),
    (50, $c26$The last surviving soldier has rank 45. What is the smallest number of soldiers that could have been on the ship?$c26$, 90);

  insert into c26_hints (id, body_md) values
    (1, $c26$REVERSE THE PIPELINE: The last encryption step was reversing the entire string, so undo that step first. Then undo the letter-number transformation.$c26$),
    (2, $c26$MODULAR SHIFT: Convert each ciphertext letter to A = 0, …, Z = 25. To reverse x ↦ (x + 7) mod 26, compute (x − 7) mod 26 for every letter. Restore the spaces using the familiar phrase.$c26$),
    (3, $c26$REPEATED SQUARING: For Part A, calculate B² and B⁴ modulo p, then combine them to obtain B⁶. Reduce modulo p after each multiplication.$c26$),
    (4, $c26$RSA MODULAR EXPONENTIATION: For Part B, use the binary expansion of 27 = 16 + 8 + 2 + 1. Repeatedly square 12 modulo 55 and multiply the powers corresponding to those exponents, reducing modulo 55 each time.$c26$),
    (5, $c26$SPLIT BY THE LAST BIT: For strings that forbid '00', count valid strings ending in 1 separately from those ending in 0. A string ending in 0 must have a 1 immediately before it, so remove the final 10 and count the valid prefix that remains.$c26$),
    (6, $c26$GENERALIZE TO THREE ZEROS: When '000' is forbidden, every valid string must end in one of the suffixes 1, 10, or 100 (apart from short base cases). Removing those suffixes gives a three-term recurrence. Establish values for lengths 0, 1, and 2 before computing the requested totals.$c26$),
    (7, $c26$PREFIX-SUM DIFFERENCE: Let P[m] be the sum of the first m array entries. A subarray from i to j has sum P[j] − P[i−1]. It is divisible by 2008 exactly when those two prefix sums have the same remainder modulo 2008.$c26$),
    (8, $c26$COUNT MATCHING REMAINDERS: Build the frequencies Cᵣ of all 1001 prefix-sum remainders, including P[0]. If a remainder appears Cᵣ times, choose any two of those indices to form a valid subarray, giving C(Cᵣ, 2) = Cᵣ(Cᵣ − 1)/2. Sum over all remainders; this avoids checking every pair of array endpoints.$c26$),
    (9, $c26$FORBIDDEN-CELL BOARD: Represent a permutation as a 6 × 6 board with one selected cell in every row and column. The six diagonal cells are forbidden, and the extra firewall rules forbid (1, 2) and (2, 3). The desired count can be obtained by inclusion–exclusion over these eight forbidden cells.$c26$),
    (10, $c26$ROOK NUMBERS & INCLUSION–EXCLUSION: Let rₖ be the number of ways to place k non-attacking rooks on the eight forbidden cells. Then the number of valid permutations is Σₖ₌₀⁶ (−1)ᵏ rₖ(6 − k)!. Count the rₖ by selecting forbidden cells with no shared row or column, then substitute into the sum.$c26$),
    (11, $c26$TOPIC: This problem uses M/G/1 queueing theory. Calculate the server’s utilization and account for variability in service time.$c26$),
    (12, $c26$FORMULA: Use the Pollaczek–Khinchine formula: Wq = λE[S²] / [2(1 − ρ)], where λ is the arrival rate and ρ = λE[S].$c26$),
    (13, $c26$TOPIC: This problem involves busy-period analysis and regenerative processes in queueing theory. A busy period lasts from the first arrival to an empty counter until the counter becomes empty again.$c26$),
    (14, $c26$FORMULA: For an M/G/1 queue, the expected busy-period duration is E[B] = E[S] / (1 − ρ). Little’s law gives Lq = λWq. Use these relationships carefully to determine the expected accumulated queue area during a busy period$c26$),
    (15, $c26$HINT 1 — TOPIC: This problem combines queueing theory and differential calculus. Express dissatisfaction as a function of the probability of choosing the fast plate, then minimize it.$c26$),
    (16, $c26$HINT 2 — FORMULA: For a differentiable objective D(q), find an interior minimum by solving dD(q)/dq = 0. Compare dissatisfaction before and after optimization, then multiply the per-student reduction by the arrival rate.$c26$),
    (17, $c26$TOPIC: This problem uses probability, state transitions, and first-step analysis. Track how much of the target sequence has been matched by the most recent dinners.$c26$),
    (18, $c26$FORMULA: Use the first-step expectation equation Eᵢ = 1 + Σⱼ pᵢⱼEⱼ, where Eᵢ is the expected number of additional dinners from state i and pᵢⱼ is the probability of moving from state i to state j. The completed-pattern state has expected additional waiting time zero.$c26$),
    (19, $c26$TOPIC: This problem involves stratified sampling and constrained optimization. The hostels have different population weights and interview costs, so equal sample sizes may not be optimal.$c26$),
    (20, $c26$FORMULA: The variance is V(ȳ) = Σₕ(Wₕ²Sₕ²/nₕ). For minimum variance with unequal sampling costs, use the cost-optimal allocation nₕ ∝ WₕSₕ/√cₕ, together with the total budget constraint.$c26$),
    (21, $c26$— TOPIC: A sum of function values multiplied by a shrinking interval width can converge to a definite integral; this is a Riemann sum.$c26$),
    (22, $c26$FORMULA: Once you obtain the integral, use the symmetry property of definite integrals known as King’s property.$c26$),
    (23, $c26$TOPIC: An infinite series involving powers of n can sometimes be generated by repeatedly differentiating a simpler power series.$c26$),
    (24, $c26$FORMULA: Start with Σₙ₌₁^∞ xⁿ = x/(1 − x). Differentiate until the required power of n appears, then substitute x = 1/2.$c26$),
    (25, $c26$TOPIC: When constant and linear terms cancel, a second-order expansion determines the limit.$c26$),
    (26, $c26$FORMULA: Use JEE expansions of ln(1 + x) and eˣ, retaining terms through order x².$c26$),
    (27, $c26$TOPIC: Matrix entries depend on the distance between indices; exploit the structure rather than expanding the determinant directly.$c26$),
    (28, $c26$FORMULA: Use determinant-preserving elementary operations: subtract consecutive rows, then consecutive columns, to create zeros.$c26$),
    (29, $c26$TOPIC: As n grows, xⁿ is negligible for most of [0, 1], while values near x = 1 dominate.$c26$),
    (30, $c26$FORMULA: Try t = xⁿ. After substitution use t^(1/n) → 1 for 0 < t ≤ 1, and evaluate the resulting integral carefully.$c26$),
    (31, $c26$TOPIC: A line in 3D space has a direction vector. Think about what rotating a line around the z-axis changes—and what it leaves unchanged.$c26$),
    (32, $c26$FORMULA/METHOD: The direction vector is (0, 4, 3). A rotation about the z-axis preserves the z-component and the magnitude of the horizontal component. Can the resulting direction become parallel to the z-axis?$c26$),
    (33, $c26$TOPIC: To locate the top of the pole, convert its direction vector into a unit vector first. Then use the pole’s length to calculate the displacement from its base.$c26$),
    (34, $c26$FORMULA/METHOD: For direction vector v and pole length L, the displacement is d = L(v/|v|). Add this displacement to the base point to find the top. Then form the line passing through the bank and the top of the pole.$c26$),
    (35, $c26$TOPIC: The boundary of an elliptical garden is described by an equation relating the x- and y-coordinates. Since the ball travels parallel to the negative x-axis, one coordinate stays constant throughout its path.$c26$),
    (36, $c26$FORMULA/METHOD: Use x²/25² + y²/15² = 1. The ball starts at (30, 12, 0), and its y-coordinate remains 12. Substitute y = 12, solve for x, and choose the first boundary point reached while moving in the negative x-direction.$c26$),
    (37, $c26$TOPIC: An ellipse can be parameterized using an angle called the eccentric angle. The x- and y-coordinates are scaled by different semi-axes.$c26$),
    (38, $c26$FORMULA/METHOD: Use x = a cos θ and y = b sin θ, where a = 25 and b = 15. Substitute the stopping point from Q4.3, find cos θ and sin θ, and choose the angle in the correct quadrant.$c26$),
    (39, $c26$TOPIC: The distance from the ellipse’s centre to the stopping point is the radius of the circular sector. Use the distance formula before calculating the area.$c26$),
    (40, $c26$FORMULA/METHOD: For a point (x, y) measured from the origin, r = √(x² + y²). The area of a sector with angle α in degrees is A = (α/360°)πr². Use the stopping point from Q4.3 and α = 30°.$c26$),
    (41, $c26$TOPIC: Think of the two cards as a sequence of draws. The first card can be any card, so focus on what the first draw tells you about the second.$c26$),
    (42, $c26$METHOD: Once the first card is known, count how many of the remaining cards share its rank, out of the total number of cards left in the deck.$c26$),
    (43, $c26$TOPIC: The first card establishes a suit. Consider which property of that card must match for the two cards to be suited.$c26$),
    (44, $c26$METHOD: Each suit contains 13 cards. After drawing the first card, count how many cards of that same suit remain among the undealt cards.$c26$),
    (45, $c26$TOPIC: In a zero-sum game, an optimal mixed strategy makes the opponent indifferent between the actions they choose with positive probability.$c26$),
    (46, $c26$METHOD: Find p by equating Player B’s expected payoffs from Call and Fold. Find q by equating Player A’s expected payoffs from Bluff and Play Safe. Solve the two equations, then calculate 300(p + q).$c26$),
    (47, $c26$TOPIC: Define one event for each opponent receiving a pocket pair of Aces or Kings. Find each event’s probability separately before combining them.$c26$),
    (48, $c26$METHOD: Apply inclusion–exclusion: P(E₁ ∪ E₂) = P(E₁) + P(E₂) − P(E₁ ∩ E₂). For the intersection, count the ways both opponents can receive valid target pairs, remembering that their hands must be disjoint.$c26$),
    (49, $c26$TOPIC: This is a permutation problem in which every card must end up in a position different from its original one.$c26$),
    (50, $c26$FORMULA: Use the derangement formula Dₙ = n! Σₖ₌₀ⁿ (−1)ᵏ/k!. Count the valid arrangements for four cards, then divide by the total number of possible arrangements.$c26$),
    (51, $c26$LOGIC: An item can make its own seat and its immediate neighbours unavailable. First find an upper bound on how many seats one item can cover, then show a placement that covers the entire row.$c26$),
    (52, $c26$FORMULA/METHOD: Each item covers at most 3 seats, so at least ceil(15/3) items are needed. Check a construction such as positions 2, 5, 8, 11, 14, and verify that every seat is either occupied or adjacent to an item.$c26$),
    (53, $c26$LOGIC: To avoid a tie, every club must have a different non-negative number of members. What is the smallest possible total if K clubs have distinct sizes?$c26$),
    (54, $c26$FORMULA/METHOD: The minimum sum of K distinct non-negative integers is 0 + 1 + ... + (K − 1) = K(K − 1)/2. Find the smallest K for which K(K − 1)/2 > 51.$c26$),
    (55, $c26$LOGIC: Fix your own 3-day selection. Count the other person’s selections that share exactly 2 days, then add the case where all 3 days match.$c26$),
    (56, $c26$FORMULA/METHOD: Total selections are C(11, 3). Exactly 2 shared days: C(3, 2)C(8, 1); exactly 3 shared days: C(3, 3)C(8, 0). Add the favourable counts, form the probability, and reduce the fraction.$c26$),
    (57, $c26$LOGIC: For a Poisson random variable, the mean and variance are both equal to its rate parameter. The question asks for the second moment, not just the mean.$c26$),
    (58, $c26$FORMULA/METHOD: Use Var(X) = E[X²] − (E[X])² and E[X] = Var(X) = λ. Rearrange to obtain E[X²] = λ + λ², then substitute the value from Question 3.$c26$),
    (59, $c26$LOGIC: Convert the score into a standard normal variable. The given cumulative probability tells you which standard-normal quantile to use.$c26$),
    (60, $c26$FORMULA/METHOD: Use Z = (Y − μ)/σ. Set (y − μ)/50 = 2, then solve for y using the mean obtained in Question 4$c26$),
    (61, $c26$TOPIC/LOGIC: The key is to understand what happens when the matrix X is applied twice. This can simplify the differential equation into familiar sine and cosine functions.$c26$),
    (62, $c26$METHOD/FORMULA: Calculate X² first, then use w(t) = e^(tX)w(0) to derive w(t). Evaluate w(t + π/2), subtract w(t), and maximize the resulting trigonometric expression.$c26$),
    (63, $c26$TOPIC/LOGIC: Use the geometry of the ellipse and the quadrilateral formed by four equally spaced trajectory points. The percentage error compares their enclosed areas.$c26$),
    (64, $c26$METHOD/FORMULA: The ellipse has semi-axes a and b, so its area is πab. Find the quadrilateral’s area from its vertices, then compute floor(100 × (ellipse area − quadrilateral area)/(ellipse area)).$c26$),
    (65, $c26$TOPIC/LOGIC: Factor the numerator and denominator as sums or differences of cubes. Look for cancellation between neighbouring factors after reindexing.$c26$),
    (66, $c26$METHOD/FORMULA: Use n³ − 1 = (n − 1)(n² + n + 1) and n³ + 1 = (n + 1)(n² − n + 1). Write the partial product through n = N, reindex the quadratic factors where possible, and take the limit as N tends to infinity.$c26$),
    (67, $c26$TOPIC/LOGIC: Expand the logarithm as a power series on 0 ≤ x < 1, then integrate the resulting terms.$c26$),
    (68, $c26$METHOD/FORMULA: Use ln(1 − x) = −∑ from n = 1 to ∞ of xⁿ/n. After dividing by x and integrating term-by-term, connect the result to the Basel sum ∑1/n².$c26$),
    (69, $c26$TOPIC/LOGIC: Use the power-series expansion of ln(1 − u)/u, with u = xyz. The product structure lets the triple integral separate into three one-dimensional integrals.$c26$),
    (70, $c26$METHOD/FORMULA: For |u| < 1, ln(1 − u)/u = −∑ from k = 1 to ∞ of u^(k−1)/k. Integrate each term over x, y, and z; each one-dimensional integral contributes a factor 1/k. Compare the resulting series with ζ(n).$c26$),
    (71, $c26$TOPIC/LOGIC: This combines a circle and a parabola. Find their common tangent, then distinguish the circle’s tangency point from the parabola’s tangency point.$c26$),
    (72, $c26$METHOD/FORMULA: For the circle x² + y² = r², a tangent with slope m can be written y = mx ± r√(1 + m²). For the parabola y² = 4ax, use its tangent form y = mx + a/m. Match the line and identify both contact points; then use arc length rθ and the distance formula.$c26$),
    (73, $c26$TOPIC/LOGIC: First determine the two initial positions. Then use relative motion: a meeting occurs when the relative position can be eliminated by the relative velocity after the same elapsed time.$c26$),
    (74, $c26$METHOD/FORMULA: Write G(t) = G₀ + v_G t and R(t) = R₀ + v_R t. Set their x-coordinates equal to find t, then verify that the y-coordinates agree. Find the meeting point and use A = ½|x₁(y₂−y₃) + x₂(y₃−y₁) + x₃(y₁−y₂)|.$c26$),
    (75, $c26$TOPIC/LOGIC: Separate the timeline into the circular arc, tangent travel, portal transit, and post-portal chase. Add the durations only after calculating each one.$c26$),
    (76, $c26$METHOD/FORMULA: Use t = θ/ω for the circular arc, t = distance/speed for the tangent, add both portal delays, and then add the meeting time from Q9.2.$c26$),
    (77, $c26$TOPIC/LOGIC: At the instant of interception, the guard must be able to reach the runner’s position in the same elapsed time. Use the runner’s position as a function of time.$c26$),
    (78, $c26$METHOD/FORMULA: After t seconds, the runner is at (30 − 5t, 12t), while the guard’s maximum reachable distance is 13t. Set (30 − 5t)² + (12t)² = (13t)² and solve for the positive time.$c26$),
    (79, $c26$TOPIC/LOGIC: The entry and exit points are the endpoints of a chord of the circle. The perpendicular from the centre to a chord bisects the chord.$c26$),
    (80, $c26$METHOD/FORMULA: Find the circle’s centre and radius, then calculate the perpendicular distance d from the centre to 3x + 4y − 32 = 0 using d = |Ax₀ + By₀ + C|/√(A²+B²). The chord length is 2√(r² − d²).$c26$),
    (81, $c26$Start by finding each senior’s actual chance of accepting a ₹50 request. Then ask yourself: in how many different ways can exactly two of the four accept, and what is each way worth?$c26$),
    (82, $c26$Enumerate every way for exactly two to accept and work out its probability. Look closely at the numbers you get: is there any structure they share that makes comparing them easier? Remember that “given that” means you only look at the cases where exactly two accepted.$c26$),
    (83, $c26$Write the expected receipt as a function of the four amounts. Once the total is fixed, how many of the amounts are really free to choose?$c26$),
    (84, $c26$Reduce to the free variables and look for the point where the expected receipt stops changing. What do the resulting conditions tell you about the ratios xᵢ/kᵢ? Before you finish, check that your amounts are allowed, and that you have found a maximum rather than a minimum.$c26$),
    (85, $c26$How likely is a day with no call at all? Now think about what must happen for the first call to come on day 1, on day 2, and on day 3.$c26$),
    (86, $c26$Write out the probabilities for the first few qualifying days as numbers. Do you notice how each one relates to the one before it? Think about how you would add up infinitely many terms with that kind of pattern.$c26$),
    (87, $c26$List every possible combination of who asks and who does not. How many are there, and how many minutes does each one cost you?$c26$),
    (88, $c26$Pick out the combinations that reach 60 minutes or more and add their probabilities. You may be able to save effort by grouping the combinations: which seniors’ choices matter most for reaching 60?$c26$),
    (89, $c26$Try playing small versions of this game (for example, piles such as (1,1,0), (1,2,3), (2,2,1)). Look for a pattern in the positions where the player to move loses. Writing the pile sizes in binary may help.$c26$),
    (90, $c26$Once you know exactly when the second player wins, go through the possible splits of 14 and test each one. Be careful when counting, because the envelopes are labelled. For the message, think about how to apply a shift of k to each letter, and what happens at the end of the alphabet.$c26$),
    (91, $c26$Compare any two people’s statements. Can both be true at the same time?$c26$),
    (92, $c26$So at most one person is truthful. Rule out “nobody is truthful” by asking what person 2026 would be saying in that case. With exactly one truth-teller, count the liars. Then find which person’s claim matches that count.$c26$),
    (93, $c26$Give each person a value, 1 for truth-teller and 0 for liar. Ask what a person’s own type must be, given what their neighbours’ types are. The rule is the same whether the speaker is honest or lying.$c26$),
    (94, $c26$Rearrange it to xᵢ₊₁ = xᵢ + xᵢ₋₁. Two consecutive values then fix the whole sequence, which repeats every 3 seats. Try the four possible starting pairs, and note that 3 divides 2025. Count how many 1s each block of 3 holds and take the best.$c26$),
    (95, $c26$Write Alice’s expression as n(n + 1) + 41. Ask when 41 could divide the whole thing, and what that would make the number. For Bob, just test n = 1, 2, 3, … until it breaks. For Carol, compare with the induction proof in Proposition 2.2 of the handbook.$c26$),
    (96, $c26$If 41 divides n(n + 1), then 41 divides the whole expression, so it isn’t prime (unless it equals 41 itself). The smallest n with 41 | n(n + 1) is the first place to check. The values for n = 0 to 39 are the well-known prime run. For Bob, compare 2ⁿ with n² at n = 1, 2, 3. Carol’s claim is exactly the statement proved in Proposition 2.2, so decide whether the 1000 is added.$c26$),
    (97, $c26$Simulate n = 1 to 8 by hand and write down the survivors. Notice when the survivor resets to 1 and how it changes between resets.$c26$),
    (98, $c26$J(n) = 2(n − 2^⌊log₂n⌋) + 1, where 2^⌊log₂n⌋ is the largest power of 2 not exceeding n.$c26$),
    (99, $c26$Simulate n = 1 to 8 by hand and write down the survivors. Notice when the survivor resets to 1 and how it changes between resets.$c26$),
    (100, $c26$J(n) = 2(n − 2^⌊log₂n⌋) + 1, where 2^⌊log₂n⌋ is the largest power of 2 not exceeding n.$c26$);

  if v_themes = 0 then
    v_mode := 'installed';

    insert into themes (id, code, name, description, topics, difficulty, unlock_cost, display_order)
    select c.id, chr(64 + c.id), c.name, c.description, array['placeholder'],
           (case when c.id <= 3 then 'EASY' when c.id <= 7 then 'MEDIUM' else 'HARD' end)::difficulty,
           100, c.id
      from c26_themes c;
    get diagnostics n_themes = row_count;

    insert into questions (id, theme_id, ordinal, body_md, difficulty, reward_coins, time_limit_seconds)
    select q.id, (q.id - 1) / 5 + 1, (q.id - 1) % 5 + 1, q.body_md, t.difficulty, q.reward_coins, 240
      from c26_questions q
      join themes t on t.id = (q.id - 1) / 5 + 1;
    get diagnostics n_questions = row_count;

    insert into hints (id, question_id, tier, body_md, cost)
    select h.id, (h.id + 1) / 2, (h.id - 1) % 2 + 1, h.body_md,
           case (h.id - 1) % 2 + 1 when 1 then 20 else 40 end
      from c26_hints h;
    get diagnostics n_hints = row_count;
  else
    v_mode := 'updated';

    update themes t
       set name = c.name, description = c.description
      from c26_themes c
     where t.id = c.id
       and (t.name, t.description) is distinct from (c.name, c.description);
    get diagnostics n_themes = row_count;

    update questions q
       set body_md = c.body_md, reward_coins = c.reward_coins
      from c26_questions c
     where q.id = c.id
       and (q.body_md, q.reward_coins) is distinct from (c.body_md, c.reward_coins);
    get diagnostics n_questions = row_count;

    update hints h
       set body_md = c.body_md
      from c26_hints c
     where h.id = c.id
       and h.body_md is distinct from c.body_md;
    get diagnostics n_hints = row_count;
  end if;

  -- whichever way it went, the database now holds exactly the official content
  if (select count(*) from themes t join c26_themes c using (id)
       where (t.name, t.description) = (c.name, c.description)) <> 10
     or (select count(*) from questions q join c26_questions c using (id)
          where (q.body_md, q.reward_coins) = (c.body_md, c.reward_coins)) <> 50
     or (select count(*) from hints h join c26_hints c using (id)
          where h.body_md = c.body_md) <> 100 then
    raise exception 'official content: the database does not hold the official content after the import';
  end if;

  -- an UPDATE of existing rows is an operational change and is audited; the first INSTALL into an empty database is the database's
  -- initial content (like the seed itself) and writes no audit row, so a freshly built database has an empty audit log
  if v_mode = 'updated' and n_themes + n_questions + n_hints > 0 then
    insert into audit_events (occurred_at, actor_kind, event_type, entity_type, entity_id, payload)
    values (clock_timestamp(), 'SYSTEM', 'CONTENT_IMPORTED', 'COMPETITION', '1',
            jsonb_build_object('mode', v_mode, 'themes_changed', n_themes, 'questions_changed', n_questions,
                               'hints_changed', n_hints, 'content_sha256', '1c2133dd052a901aa6c9eae4fc2b418fa33b55b55ad9ffa7b4a423b16d17dcdb'));
  end if;
  raise notice 'official content: % themes, % questions, % hints updated (%)', n_themes, n_questions, n_hints, v_mode;

  drop table c26_themes;
  drop table c26_questions;
  drop table c26_hints;
end $c26_import$;
